### PR TITLE
fix (carousel, horizontal-scoller): remove lazy loading from images inside a carousel and horizontal scroller to prevent rendering problems

### LINKED ISSUE #2922: Carousel & Image block compatibility issue with SiteGround feature
**Describe the bug**
Related to this issue: https://secure.helpscout.net/conversation/2387903273/21535/

**Issue summary**: When adding Image blocks inside the Carousel block & the lazy loading feature is enabled on SiteGround's Speed Optimizer plugin, it causes a large white bottom part initially and a layout shift after a few seconds when it autocorrects to the correct height.

Addtl. notes:
- Issue in frontend only
- No specific theme
- No specific browser
- No specific Stackable plugin version (Tried on Stackable 3.12.1)

**To Reproduce**
1. Install and Activate Speed Optimizer plugin
Screenshot 2023-10-16 at 9 38 19 AM

2. In Speed Optimizer settings, go to Speed Optimizer > Media > Media Optimization and enable Lazy Loading
Screenshot 2023-10-16 at 9 40 02 AM

3. Add a new page
4. Add a Carousel block
5. Inside the slides, at least one image each OR copy this block code: 
[carousel block with images.txt](https://github.com/gambitph/Stackable/files/12911347/carousel.block.with.images.txt)

6. Save page
7. View frontend
8. See that there's a big space below the image and the dots are far below
9. Try clicking the next button and see if the height corrects to the actual height

**Expected behavior**
If Speed Optimizer's lazy loading feature is enabled, there should be no additional height/space below the Carousel block

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/8595d412-6dd3-4847-a912-0e86e9540631

### LINKED ISSUE #2943: [WooCommerce] Carousel block issue - When adding Product Image inside the Image block, it has an excess space below on frontend
**Describe the bug**
- When adding an Image block inside the Carousel block and fetching Product Image for the block, it adds an excess space below. But when navigating (clicking arrows or dots), it resets upon going to next slides.
   - It resets even when page is refreshed so make sure to check in Incognito while inspecting
- Reference: https://www.notion.so/Igor-Konvit-2fb713561d7d4a5c8343436f117f73b1
- Issue only on frontend

**To Reproduce**
1. Activate WooCommerce plugin
2. Add at least 5 products and make sure it has Product Image
3. Add a new page
4. Add a Carousel block OR copy these blocks (skip steps 5-6): [carousel woocommerce issue.txt](https://github.com/gambitph/Stackable/files/13065182/carousel.woocommerce.issue.txt)
5. Add at least 5 slides
6. In each slide, add an Image block
7. In each Image block, fetch dynamic content for each WooCommerce product created
8. Set "Slides to Show" for at least 2 or more (Layout > Slides to Show)
Screenshot 2023-10-23 at 9 16 12 AM

9. Save page
10. View frontend (if issue doesn't show up, open in incognito window)
11. See that there's an excess space between the Image blocks and dots
12. Try clicking the next slide
13. See that the issue disappears

**Expected behavior**
When adding Product Image inside the Image block, it should not show an excess space between the Carousel slides & dots

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/c7222f92-1a69-494b-b575-4528e4eddbcb

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2943 
fixes #2922 
fixes Horizontal Scroller

### CODE REVIEW

**Review by bfintal — CHANGES_REQUESTED** [review]
Instead of doing `str_replace` please use the new HTML API, to only add the new placeholder class: https://make.wordpress.org/core/2023/08/19/progress-report-html-api/#using-the-html-api-today

Please only add the class for the slides that are hidden

File: src/block/carousel/index.php [hunk 1]
```diff
@@ -19,3 +19,50 @@ function stackable_load_carousel_frontend_script() {
 	}
 	add_action( 'stackable/carousel/enqueue_scripts', 'stackable_load_carousel_frontend_script' );
 }
+
+if ( ! function_exists( 'stackable_carousel_add_class_images' ) ) {
```
Comment (bfintal) [inline src/block/carousel/index.php:26]:
```suggestion
// Lazy loaded images inside carousels make the carousel height buggy and show extra
// spaces because the height isn't available in lazy loaded images. Prevent images from
// hidden slides from lazy loading to prevent this.
if ( ! function_exists( 'stackable_carousel_add_class_images' ) ) {
```

File: src/block/horizontal-scroller/index.php [hunk 2]
```diff
@@ -19,3 +19,38 @@ function stackable_load_horizontalscroller_frontend_script() {
 	}
 	add_action( 'stackable/horizontal-scroller/enqueue_scripts', 'stackable_load_horizontalscroller_frontend_script' );
 }
+
+if ( ! function_exists( 'stackable_horizontal_scroller_add_class_images' ) ) {
```
Comment (bfintal) [inline src/block/horizontal-scroller/index.php:26]:
```suggestion
// Lazy loaded images inside carousels make the carousel height buggy and show extra
// spaces because the height isn't available in lazy loaded images. Prevent images from
// hidden slides from lazy loading to prevent this.
if ( ! function_exists( 'stackable_horizontal_scroller_add_class_images' ) ) {
```

File: src/block/carousel/index.php [hunk 3]
```diff
@@ -19,3 +19,53 @@ function stackable_load_carousel_frontend_script() {
...
+		$index = 1;
+		$slides_to_show = 1;
+
+		if ( ! empty( $block ) && isset( $block['attrs'] ) && is_array( $block['attrs'] ) ) {
+			if ( isset( $block['attrs']['slidesToShow'] ) ) {
+				$slides_to_show = $block['attrs']['slidesToShow'];
+			}
+		}
+
+		$block_content = new WP_HTML_Tag_Processor( $block_content );
```
Comment (bfintal) [inline src/block/carousel/index.php]: I recommend using another variable name so that we do not accidentally mutate the original value, or use it mistakenly.

```suggestion
		$html_tag = new WP_HTML_Tag_Processor( $block_content );
```

File: src/block/carousel/index.php [hunk 4]
```diff
@@ -19,3 +19,53 @@ function stackable_load_carousel_frontend_script() {
 	}
 	add_action( 'stackable/carousel/enqueue_scripts', 'stackable_load_carousel_frontend_script' );
 }
+
+// Lazy loaded images inside carousels make the carousel height buggy and show extra
+// spaces because the height isn't available in lazy loaded images. Prevent images from
+// hidden slides from lazy loading to prevent this.
+if ( ! function_exists( 'stackable_carousel_add_class_images' ) ) {
+	function stackable_carousel_add_class_images($block_content, $block) {
```
Comment (bfintal) [inline src/block/carousel/index.php]: Please fix spacing
```suggestion
	function stackable_carousel_add_class_images( $block_content, $block ) {
```

**Review by bfintal — CHANGES_REQUESTED** [review]
