### PR TITLE
Fixes icon block responsive column gap

### LINKED ISSUE #1213: Adjusting the column gap in advanced tab for mobile view - no effect
Steps to reproduce:
- Add icon block (more than 1 column)
- Go to Adv. tab > Column / Container Spacing > Column Gap
- Adjust Column Gap for mobile view
- see bug in frontend and backend

### PR DESCRIPTION
**Pull request by blankart**
Fixes #1213

### CODE REVIEW

File: src/block/icon/style.js [hunk 1]
```diff
@@ -154,7 +155,21 @@ export const createStyles = props => {
 	}
 
 	// Advanced Column Gap
-	styles.push( ...createResponsiveStyles( '.ugb-icon__content-wrapper', '%scolumnGap', 'columnGap', '%spx', props.attributes, { important: true } ) )
+	styles.push( {
+		'.ugb-icon__content-wrapper': {
+			columnGap: getValue( 'columnGap' ) !== '' ? appendImportant( getValue( 'columnGap' ) + 'px', true ) : undefined,
```
Comment (bfintal) [inline src/block/icon/style.js:160]: `getValue` should be able to format this, and `appendImportant` should be able to handle blank values.

```suggestion
			columnGap: appendImportant( getValue( 'columnGap', '%spx' ) ),
```

**Review by bfintal — CHANGES_REQUESTED** [review]
