### PR TITLE
Fix: Get default presets, add support for themes.json v3

### LINKED ISSUE #3532: Error: When opening the Stackable global settings, the editor shows an unexpected error
- Using YITH Wonder Theme
- Error coming from `extractNumbersAndUnits()` in `src/util/index.js`

### PR DESCRIPTION
**Pull request by kaeizen**
Fixes #3532

### CODE REVIEW

File: src/hooks/use-preset-controls.js [hunk 1]
```diff
@@ -31,7 +35,26 @@ const nonePreset = {
...
+		 * Therefore, we also need to get the default presets if the `defaultSizesEnabled` is `true` and merge it with the theme presets.
+		 *
+		 * https://make.wordpress.org/core/2024/06/19/theme-json-version-3/#:~:text=Breaking%20changes%20in%20version%203
+		 * */
+		wpDefaultPresets,
+		defaultSizesEnabled,
+	] = useSettings(
+		PRESET_MAPPING[ property ].settings.join( '.' ),
+		[ ...PRESET_MAPPING[ property ].settings, 'default' ].join( '.' ),
+		PRESET_MAPPING[ property ].defaultEnabled.join( '.' )
```
Comment (bfintal) [inline src/hooks/use-preset-controls.js]: Can we make this more readable?

File: src/hooks/use-preset-controls.js [hunk 2]
```diff
@@ -42,7 +65,10 @@ export const usePresetControls = property => {
 
 	// Get the theme/default presets if the user have one, else return the stackable presets
 	const basePresets = hasThemePresets
-		? themePresets
+		? ( wpDefaultPresets && defaultSizesEnabled !== false
+			? [ ...themePresets, ...wpDefaultPresets ] // merge theme and default preset sizes
+			: themePresets
+		)
```
Comment (bfintal) [inline src/hooks/use-preset-controls.js]: Can we make this more readable?

**Review by bfintal — CHANGES_REQUESTED** [review]
