### PR TITLE
fix (seo): added a filter that would add stackable to the list of compatible plugins with Rank Math

### LINKED ISSUE #2424: SEO Issues - Table of Contents block is not detected in Rank Math > Content Readability
SEO Plugin: Rank Math

**To Reproduce**
1. Install and activate SEO Press plugin
2. Add a new post
3. Copy this code to your post
[SEO testing with TOC block.txt](https://github.com/gambitph/Stackable/files/9534897/SEO.testing.with.TOC.block.txt)
4. Click this:
    image
5. Scroll down to see Content Readability section
6. Check if this error is present: “Use Table of Content to break-down your text.” even if you have an existing Table of Contents block
    image

**Expected behavior**
Table of Contents block should be detected by Rank Math SEO plugin.

### PR DESCRIPTION
**Pull request by prconcepcion**
Fixes #2424

### CODE REVIEW

File: src/block/table-of-contents/index.php [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * @param array TOC plugins.
+ */
+if ( ! defined( 'ABSPATH' ) ) {
+	exit;
+}
+
+add_filter( 'rank_math/researches/toc_plugins', function( $toc_plugins ) {
+       $toc_plugins['Stackable/plugin.php'] = 'Stackable';
+    return $toc_plugins;
+});
```
Comment (bfintal) [inline src/block/table-of-contents/index.php:15]:
```suggestion
} );
```

**Comment by andeng1106** [comment]
@prconcepcion TOC block is not yet detected by Rank Math. I tried using an old page with TOC block and a new page and added a TOC block. Both didn't work.

Rank Math version: Version 1.0.99

https://user-images.githubusercontent.com/103395655/195041380-d6875cbb-be59-4b0d-b8c6-091138055b43.mp4
