### PR TITLE
fix(posts): also return original selectors to avoid overwriting

### LINKED ISSUE #3421: Posts Block - Featured Image Color Overlay does not appear in frontend
**Describe the bug**
- Overlay color in Featured image section under the Style tab does not show in frontend
- Happens only in frontend

**To Reproduce**
1. Add a post
2. Add a Featured image
3. Under Settings, enable Link to Post
4. Add a page
5. Add a Posts Block
6. On Style > Featured Image, pick any Overlay Color
7. Check if Overlay Color applies on editor then Save
8. See error on frontend (no overlay color applied on the featured image)

**Expected behavior**
The overlay color in the Featured Image should be visible on the frontend

**Screenshots**

Image

Image

### LINKED ISSUE #3422: Posts Block – Featured Image Overlay Opacity not visible in editor and frontend
**Describe the bug**
- Overlay opacity in Featured image section under the Style tab does not appear
- Happens in editor 
- Happens in frontend
- Happens in Normal and Hovered State

**To Reproduce**
1. Add a post
2. Add a Featured image
3. Under Settings, enable Link to Post
4. Add a page
5. Add a Posts Block
6. On Style > Featured Image, increase Overlay Opacity in Normal State
7. See error in editor (no Overlay Opacity is applied)
10. See error in frontend (no Overlay Opacity is applied)
11. On Style > Featured Image, increase Overlay Opacity in Hover State
12. See error in editor (no Overlay Opacity is applied)
13. See error in frontend (no Overlay Opacity is applied)

**Expected behavior**
The overlay opacity in the Featured Image should be visible in both the editor and the frontend

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by Arukuen**
fixes #3421
fixes #3422

### CODE REVIEW

**Comment by Arukuen** [comment]
Why do we need a different selector for the `list` variation? The featured image for all the variations have the same structure, which requires the selector to be `.stk-img-wrapper` to target the proper blocks. Using a different selector for `list` makes the style not target properly. 

For the meantime, I just added the selector from `props`, along with the different selector for `list`.

File: src/block/posts/style.js [hunk 1]
```diff
@@ -294,15 +294,34 @@ Image.addStyles( blockStyles, {
...
+	// 	if ( [ 'list' ].includes( blockStyle?.name ) && imageHasLink ) {
+	// 		if ( Array.isArray( selector ) ) {
+	// 			return selector.map( sel =>
+	// 				sel.replace( '.stk-img-wrapper', `${ itemSelector } .stk-block-posts__image-link ` )
+	// 			)
+	// 		}
+	// 		return [ '.stk-img-wrapper', selector.replace( '.stk-img-wrapper', `${ itemSelector } .stk-block-posts__image-link` ) ]
+	// 	}
+	// 	return selector
+	// },
```
Comment (bfintal) [inline src/block/posts/style.js]:
```suggestion
```

**Comment by bfintal** [comment]
> Why do we need a different selector for the `list` variation? The featured image for all the variations have the same structure, which requires the selector to be `.stk-img-wrapper` to target the proper blocks. Using a different selector for `list` makes the style not target properly.

From what I remember, the list variation had a different structure that prevented image styles from being applied.
