### PR TITLE
fix (dynamic-breakpoints): prevent dynamic breakpoints from being modified repeatedly

### LINKED ISSUE #2944: Column Width & Responsive breakpoint issue - It doesn’t show changes for tablet settings on frontend if mobile breakpoint is set to 1024px
**Describe the bug**
- If I set breakpoints to Tablet: 1200px & Mobile: 1024px and I changed column widths for all responsive views. When changing responsive view on frontend in between 1200px & 1024px (e.g. 1100px), the breakpoint jumps to mobile preview instead of showing the tablet preview.
- Issue only for column width, ok when changing font size & other settings
- Issue only on frontend

**To Reproduce**
1. In Stackable settings, set responsive breakpoints to:
   - Tablet: 1200px
   - Mobile: 1024px
2. Add a new page
3. Add a Columns block
4. Add at least 2 inner columns
5. Set Column width for each responsive view & both inner columns:
   - Desktop: 16% 84%
   - Tablet: 25% 75%
   - Mobile: 100% 100%
6. Save page
7. View frontend
8. Click Inspect Element & click Toggle Device toolbar to view responsive mode (see [page](https://ffeathers.wordpress.com/2016/04/16/set-size-of-browser-inner-window-for-screenshots-in-chrome/#:~:text=Open%20Chrome%20Developer%20Tools.,right%20next%20to%20the%20dropdown.) for guide)
Screenshot 2023-10-23 at 10 06 36 AM

9. Choose Dimensions to "Responsive"
10. Set first Dimension to "1100px"
Screenshot 2023-10-23 at 10 09 59 AM

11. See that it's showing the changes from mobile instead of tablet

**Expected behavior**
- It should show tablet settings on frontend if mobile breakpoint is 1024px
- Here's an example if mobile breakpoint is 1000px:

https://github.com/gambitph/Stackable/assets/103395655/0175f936-59a2-48f8-8f34-f4baa38ee8e1

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/36e8303d-42d9-4943-b222-1c0139c72b0f

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2944

### CODE REVIEW

File: src/dynamic-breakpoints.php [hunk 1]
```diff
@@ -131,16 +131,42 @@ public function adjust_breakpoints( $css ) {
...
-				$css = preg_replace( "/(@media[^{]+)width:\s*767px/", "$1width:" . ( $new_mobile - 1 ). "px", $css );
+			if ( $new_tablet === '1024' && $new_mobile === '768' ) {
+				return $css;
 			}
 
+			// Check if css still have the default tablet and mobile breakpoints
+			$has_default_tablet = strpos( $css, 'width:1024px)' ) !== false || strpos( $css, 'width:1023px)' ) !== false;
+			$has_default_mobile = strpos( $css, 'width:768px)' ) !== false || strpos( $css, 'width:767px)' ) !== false;
+
+            if ( ! empty( $new_tablet ) && $has_default_tablet ) {
```
Comment (bfintal) [inline src/dynamic-breakpoints.php]: I suggest placing the `stripos` stuff inside the `if` statement since those aren't really necessary if there's no `$new_tablet` provided. Please also do the same with mobile

```
if ( ! empty( $new_tablet ) ) {
	// Check if css still have the default tablet and mobile breakpoints
	$has_default_tablet = strpos( $css, 'width:1024px)' ) !== false || strpos( $css, 'width:1023px)' ) !== false;
	$has_new_tablet = strpos( $css, 'width:' . $new_tablet . 'px)' ) !== false;
	$has_new_tablet_minus_1 = strpos( $css, 'width:' . ( $new_tablet - 1 ) . 'px)' ) !== false;
	if ( $has_default_tablet && ! $has_new_tablet  ) {
```

**Review by bfintal — CHANGES_REQUESTED** [review]
Please see my comment, also please fix indentation. Use tabs instead of spaces for indentation
