### PR TITLE
fix: remove dynamic content in customizer

### LINKED ISSUE #3352: Disable Dynamic Content in Theme Customizer
**Describe the bug**
- Dynamic Content seems to not be working anymore in Theme Customizer > Header & Footer Widgets
- Issue happens when selecting Dynamic Content in Theme Customizer via:
    - Toolbar
    - Inspector (Toolbar > More Options > Show more settings)
- Applies to themes with Theme Customizer such as but not limited to:
    - Blocksy
    - Twenty Twenty One Theme
    - Astra
    - OceanWP
    - etc...

**To Reproduce**
1. Activate any theme with theme customizer (e.g Blocksy)
2. Go to Theme > Customize
3. Go to Footer (Blocksy widgets are in footer)
4. Add any Stackable block with text / image / video (e.g. Heading)
5. Use Dynamic Content via Toolbar
6. See that it just glitches
7. Use Dynamic Content via inspector (Toolbar > More Options > Show more settings)
8. See that it's showing "No block selected"

**Expected behavior**
- Disable Dynamic Content in Theme Customizer
- Should be disabled in:
    - Toolbar
    - Inspector (Toolbar > More Options > Show more settings)

**Screenshots**

https://github.com/user-attachments/assets/3c89ecb6-8b2b-48d1-8524-f229c6e90679

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3352

### CODE REVIEW

File: src/components/dynamic-content-control/index.js [hunk 1]
```diff
@@ -499,6 +499,9 @@ export const useValueWithFieldsTitle = ( value = '' ) => {
 const dynamicContent = <SVGDatabaseIcon />
 
 export const DynamicContentButton = memo( props => {
+	if ( select( 'core/customize-widgets' ) ) {
```
Comment (bfintal) [inline src/components/dynamic-content-control/index.js:503]:
```suggestion
	// Hide the button if inside the Customizer
	if ( select( 'core/customize-widgets' ) ) {
```
