### PR TITLE
fix/feat (tabs): added option to make tabs labels layout more customizable

### LINKED ISSUE #2739: Tabs block > Tab Labels - Text Alignment settings issue for vertical orientation & icon position
**Describe the bug**
If Tab Orientation is set to "Vertical" and Icon Position is set to "Left" or "Right", Text Alignment settings doesn't work.

It works if I enable Full Width for Tab Labels (make sure to switch Tab Orientation to "Horizontal" to see setting).
Screenshot 2023-07-17 at 10 45 28 AM

https://github.com/gambitph/Stackable/assets/103395655/e739fcd5-b876-4c11-8929-a00fd87e49c1

**To Reproduce**
1. Add a new page
2. Add Tabs block
3. Set Tab Orientation to "Vertical"
4. Go to Tab Labels and enable Icon
5. In Tab Labels > Layout, change Icon Position to "Left" or "Right"
6. Change Text Alignment setting to any
7. See that it doesn't change (text doesn't move)

**Expected behavior**
- Text Alignment settings should work for Vertical Orientation whether Full Width is enabled or disabled.
- If changing Text Alignment settings, you should be able to do these two scenarios:
   - icons are aligned to the right, but the text are all aligned to the left
   - icons are aligned to the left, and all the text are aligned to the right
   - Sample is the screenshot below:
image

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/6cf9a7b7-b9a6-483e-b1e2-0218a1d2f2cc

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2739

### CODE REVIEW

File: src/block/tab-labels/schema.js [hunk 1]
```diff
@@ -114,6 +114,17 @@ export const attributes = ( version = VERSION ) => {
...
+		attributes: {
+			fixedIconPosition: {
+				type: 'string',
+				default: '',
+			},
+		},
+		versionAdded: '3.0.0',
+		versionDeprecated: '',
+	} )
+
```
Comment (bfintal) [inline src/block/tab-labels/schema.js:127]: You can combine this into the add method above

Comment (bfintal) [inline src/block/tab-labels/schema.js:127]: You can combine this into the add method above

File: src/block/tab-labels/style.js [hunk 2]
```diff
@@ -125,7 +125,7 @@ const Styles = props => {
 				} }
 				attrName="contentAlign"
 				key="iconAlignment-iconPosition"
-				enabledCallback={ getAttribute => getAttribute( 'fullWidth' ) || getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom' }
+				enabledCallback={ getAttribute => getAttribute( 'fullWidth' ) || ! getAttribute( 'fullWidth' ) || getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom' }
```
Comment (bfintal) [inline src/block/tab-labels/style.js:128]: You have both fullWidth and ! fullWidth

File: src/block/tab-labels/style.js [hunk 3]
```diff
@@ -179,6 +179,22 @@ const Styles = props => {
...
+			<BlockCss
+				{ ...propsToPass }
+				enabledCallback={ getAttribute => getAttribute( 'iconPosition' ) === '' || getAttribute( 'iconPosition' ) === 'right' }
+				selector=".stk-block-tab-labels__wrapper .stk-block-tab-labels__text"
+				styleRule="width"
+				attrName="fixedIconPosition"
+				valueCallback={ value => {
+					if ( value ) {
+						return '100%'
+					}
```
Comment (bfintal) [inline src/block/tab-labels/style.js:192]: This needs a return if it doesn't fit the condition

File: src/block/tab-labels/style.js [hunk 4]
```diff
@@ -179,6 +179,22 @@ const Styles = props => {
...
+				} }
+				key="fixedIconPosition"
+				responsive="all"
+				dependencies={ [ 'iconPosition' ] }
```
Comment (bfintal) [inline src/block/tab-labels/style.js:196]: Spread ...dependencies here (extract dependencies from the props argument)

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/block/tab-labels/style.js [hunk 5]
```diff
@@ -179,6 +183,23 @@ const Styles = props => {
...
+				{ ...propsToPass }
+				enabledCallback={ getAttribute => getAttribute( 'iconPosition' ) === '' || getAttribute( 'iconPosition' ) === 'right' }
+				selector=".stk-block-tab-labels__wrapper .stk-block-tab-labels__text"
+				styleRule="width"
+				attrName="fixedIconPosition"
+				valueCallback={ value => {
+					if ( value ) {
+						return '100%'
+					}
+					return undefined
```
Comment (bfintal) [inline src/block/tab-labels/style.js:197]:
```suggestion
					return value
```

File: src/block/tab-labels/style.js [hunk 6]
```diff
@@ -69,7 +73,7 @@ const Styles = props => {
 			/>
 			<BlockCss
 				{ ...propsToPass }
-				selector=""
+				selector=":is(.stk-block-content.stk-block-tabs--horizontal) .%s"
```
Comment (bfintal) [inline src/block/tab-labels/style.js:76]: I think you were supposed to remove this

File: src/block/tab-labels/style.js [hunk 7]
```diff
@@ -148,7 +152,7 @@ const Styles = props => {
 					return newValue
 				} }
 				responsive="all"
-				dependencies={ [ 'fullWidth', 'iconPosition' ] }
+				dependencies={ [ 'fullWidth', 'iconPosition', ...dependencies ] }
```
Comment (bfintal) [inline src/block/tab-labels/style.js:155]:
```suggestion
				dependencies={ [
					'fullWidth',
					'iconPosition',
					...dependencies
				] }
```

File: src/block/tab-labels/style.js (hunk 5 above)
Comment (bfintal) [inline src/block/tab-labels/style.js:197]:
```suggestion
					return value ? '100%' : undefined
```

File: src/block/tab-labels/style.js [hunk 8]
```diff
@@ -179,6 +183,23 @@ const Styles = props => {
...
+				attrName="fixedIconPosition"
+				valueCallback={ value => {
+					if ( value ) {
+						return '100%'
+					}
+					return undefined
+				} }
+				key="fixedIconPosition"
+				responsive="all"
+				dependencies={ [ 'iconPosition', ...dependencies ] }
```
Comment (bfintal) [inline src/block/tab-labels/style.js:201]:
```suggestion
				dependencies={ [
					'iconPosition',
					 ...dependencies
				] }
```

File: src/block/tab-labels/style.js [hunk 9]
```diff
@@ -125,7 +129,7 @@ const Styles = props => {
 				} }
 				attrName="contentAlign"
 				key="iconAlignment-iconPosition"
-				enabledCallback={ getAttribute => getAttribute( 'fullWidth' ) || getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom' }
+				enabledCallback={ getAttribute => getAttribute( 'fullWidth' ) !== undefined || getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom' }
```
Comment (bfintal) [inline src/block/tab-labels/style.js:132]: Is this correct? I remember seeing initially this in your earlier commit:

```js
getAttribute( 'fullWidth' ) || ! getAttribute( 'fullWidth' ) || getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom' ```

which can be simplified to

```js
getAttribute( 'iconPosition' ) === 'top' || getAttribute( 'iconPosition' ) === 'bottom'
```

..But this new commit has `getAttribute( 'fullWidth' ) !== undefined`

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/block/tab-labels/schema.js [hunk 10]
```diff
@@ -109,6 +109,10 @@ export const attributes = ( version = VERSION ) => {
 				default: '',
 				stkHover: true,
 			},
+			fixedIconPosition: {
+				type: 'string',
```
Comment (bfintal) [inline src/block/tab-labels/schema.js:113]:
```suggestion
				type: 'boolean',
```
