### PR TITLE
fix: accordion block close animation

### LINKED ISSUE #2728: Accordion block - Animation doesn't work when closing accordion inside Columns block
**Describe the bug**
If Accordion block is nested inside Columns block, animation doesn't work when closing accordion.

**To Reproduce**
1. Add a new page
2. Add a Columns block
3. Inside the Columns block, add 2 or 3 accordion blocks (any layout)
4. Save and view page
5. Try expanding then closing accordion
6. Observe if there's animation

**Expected behavior**
When expanding then closing accordion, the animation is smooth

https://github.com/gambitph/Stackable/assets/103395655/b5e74be9-f5b4-4f30-aad6-042ca1a3c5fc

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/a1e28ca6-1e31-4717-a634-0f64920786cf

### PR DESCRIPTION
**Pull request by mxkae**
fixes #2728

### CODE REVIEW

**Review by bfintal — CHANGES_REQUESTED** [review]
Instead of animating things completely differently if `! doWrapHack`, I would suggest doing this instead, so that our main animating code doesn't double:

```js
const doWrapHack = !! el.closest( '.stk-block-columns' )

if ( doWrapHack ) {
    addWrapperHack( ... )
}

// animate

if ( doWrapHack ) {
    removeWrapperHack( ... )
}
```

File: src/block/accordion/frontend-accordion.js [hunk 1]
```diff
@@ -30,6 +30,13 @@ class StackableAccordion {
 					el.doAnimate = false
 					const preHeight = el.dataset.preHeight
 
+					const doWrapHack = !! el.closest( '.stk-block-columns' )
```
Comment (bfintal) [inline src/block/accordion/frontend-accordion.js:33]:
```suggestion
					// When inside columns, flex prevents the accordion closing animation, this hack fixes it.
					const doWrapHack = !! el.closest( '.stk-block-columns' )
```

**Comment by andeng1106** [comment]
@mxkae Animation when expanding/collapsing accordion is now fixed.

Remaining issue: 
Arrow animation when Accordion is inside the Columns is now different vs. Accordion is outside the Columns block
- Expected arrow animation: when Accordion is outside Columns block
https://github.com/gambitph/Stackable/assets/103395655/9e3dcddd-78b9-4590-b840-356e204cb2c0
