### PR TITLE
fix/3504 responsive typescale

### LINKED ISSUE #3504: Type Scale: add responsive capabilities
Currently, changing the **Type Scale** only changes the desktop values. We need to make it so that you can also change tablet and mobile type scales.

### PR DESCRIPTION
**Pull request by Arukuen**
fixes #3504

### CODE REVIEW

File: src/plugins/global-settings/typography/utils.js [hunk 1]
```diff
@@ -6,26 +60,51 @@
...
-		h2: { fontSize: String( Math.pow( typeScale, 5 ).toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		h3: { fontSize: String( Math.pow( typeScale, 4 ).toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		h4: { fontSize: String( Math.pow( typeScale, 3 ).toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		h5: { fontSize: String( Math.pow( typeScale, 2 ).toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		h6: { fontSize: String( typeScale.toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		p: { fontSize: '1', fontSizeUnit: 'rem' },
-		'.stk-subtitle': { fontSize: String( ( 1 / typeScale ).toFixed( 3 ) ), fontSizeUnit: 'rem' },
-		'.stk-button__inner-text': { fontSize: '1', fontSizeUnit: 'rem' },
+
+	const headings = {
```
Comment (bfintal) [inline src/plugins/global-settings/typography/utils.js:77]:
```suggestion
	// These values are the exponent for the typeScale value
	const headings = {
```
