### PR TITLE
fix (WP6.3): prevent PHP error from appearing

### LINKED ISSUE #2753: [WP 6.3] If `WP_DEBUG` is set to `true`, Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string… error appears
**Describe the bug**
- Errors shows only in site editor
- Happens only for Twenty Twenty Three Theme

**To Reproduce**
1. In local site folder, go to app > public > wp-config.php
2. Add `define( 'WP_DEBUG', true ); ` (below `/* Add any custom values between this line and the "stop editing" line. */` comment)
3. Save file
4. Go back to site
5. Make sure theme is Twenty Twenty Three
6. View home page
7. See errors

**Screenshots**
- Based on the error, it seems to be related with Dynamic Content

https://github.com/gambitph/Stackable/assets/103395655/d562adc1-3822-47bb-93c2-0d9ba6d6f18d

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2753

### CODE REVIEW

File: src/fonts.php [hunk 1]
```diff
@@ -19,6 +19,10 @@ function __construct() {
 		}
 
 		public function gather_google_fonts( $block_content, $block ) {
+			if ( $block_content === null ) {
+				return $block_content;
+			}
+
```
Comment (bfintal) [inline src/fonts.php:25]: Please remove, the block_content isn't actually used here, might cause fonts to stop loading

File: src/init.php [hunk 2]
```diff
@@ -188,6 +188,10 @@ public function load_frontend_scripts_conditionally_head() {
 		 * @return string output block
 		 */
 		public function load_frontend_scripts_conditionally( $block_content, $block ) {
+			if ( $block_content === null ) {
+				return $block_content;
+			}
+
```
Comment (bfintal) [inline src/init.php:194]: Same as above, please just handle when block_content is null because this will skip some processes

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/deprecated/v2/init.php [hunk 3]
```diff
@@ -364,6 +368,10 @@ function register_frontend_blog_posts_block_compatibility_v2() {
 	 * @return string The block content
 	 */
 	function stackable_frontend_v2_try_migration( $block_content, $block ) {
+		if ( $block_content === null ) {
+			$block_content = '';
```
Comment (bfintal) [inline src/deprecated/v2/init.php:372]:
```suggestion
			return $block_content;
```

File: src/deprecated/v2/init.php [hunk 4]
```diff
@@ -312,6 +312,10 @@ function stackable_add_required_block_styles_v2() {
 if ( ! function_exists( 'load_frontend_scripts_conditionally_v2') ) {
 
 	function load_frontend_scripts_conditionally_v2( $block_content, $block ) {
+		if ( $block_content === null ) {
+			$block_content = '';
```
Comment (bfintal) [inline src/deprecated/v2/init.php:316]:
```suggestion
			return $block_content;
```

File: src/deprecated/v2/optimization-settings.php [hunk 5]
```diff
@@ -85,6 +85,10 @@ public function disable_frontend_scripts() {
 		 * @since 2.17.0
 		 */
 		public function load_frontend_scripts_conditionally( $block_content, $block ) {
+			if ( $block_content === null ) {
+				$block_content = '';
```
Comment (bfintal) [inline src/deprecated/v2/optimization-settings.php:89]:
```suggestion
				return $block_content;
```

**Review by bfintal — CHANGES_REQUESTED** [review]
