### PR TITLE
Icon block column gap fix

### LINKED ISSUE #783: column gap is not working on Icon Block
column gap is not working on Icon Block

### PR DESCRIPTION
**Pull request by blankart**
Fixes #783

### CODE REVIEW

File: src/block/icon/style.js [hunk 1]
```diff
@@ -92,6 +93,23 @@ export const createStyles = props => {
...
+				columnGap: appendImportant( getValue( 'tabletColumnGap', '%spx' ) ),
+			},
+		},
+		mobile: {
+			'.ugb-icon__content-wrapper': {
+				columnGap: appendImportant( getValue( 'mobileColumnGap', '%spx' ) ),
+			},
+		},
+	} )
+
```
Comment (bfintal) [inline src/block/icon/style.js:112]: You can use `createResponsiveStyles` here to compress this whole thing into just 1 line.

File: src/block/icon/style.js [hunk 2]
```diff
@@ -92,6 +92,9 @@ export const createStyles = props => {
 		styles.push( ...createResponsiveStyles( '.ugb-icon__title', 'title%sBottomMargin', 'marginBottom', '%spx', props.attributes, true ) )
 	}
 
+	// Advanced Column Gap
+	styles.push( ...createResponsiveStyles( '.ugb-icon__content-wrapper', '%scolumnGap', 'columnGap', '%spx', props.attributes, true ) )
```
Comment (bfintal) [inline src/block/icon/style.js:96]:
```suggestion
	styles.push( ...createResponsiveStyles( '.ugb-icon__content-wrapper', '%scolumnGap', 'columnGap', '%spx', props.attributes, { important: true } ) )
```

File: src/block/icon/style.js [hunk 3]
```diff
@@ -92,6 +92,9 @@ export const createStyles = props => {
 		styles.push( ...createResponsiveStyles( '.ugb-icon__title', 'title%sBottomMargin', 'marginBottom', '%spx', props.attributes, true ) )
 	}
 
+	// Advanced Column Gap
+	styles.push( ...createResponsiveStyles( '.ugb-icon__content-wrapper', '%scolumnGap', 'columnGap', '%spx', props.attributes, { important: true } ) )
```
Comment (bfintal) [inline src/block/icon/style.js:96]:
```suggestion
	styles.push( ...createResponsiveStyles( '.ugb-icon__content-wrapper', '%scolumnGap', 'columnGap', '%spx', props.attributes, true ) )
```
