### PR TITLE
fix (video popup): change button tag with div tag

### LINKED ISSUE #3055: Stackable adds a button HTML element when using the video popup, creates a box-shadow when on mouse over
**_Note: This issue is from the affiliate who encountered bugs when testing out Stackable_**

Reference: https://www.notion.so/Stackable-adds-a-button-HTML-element-when-using-the-video-popup-creates-a-box-shadow-when-on-mouse--cd4fcf6828f046fc8f807481f6b6eaa7

For the video popup, Stackable adds a "button" HTML element for the video poster (which is probably not a very good idea as it can lead to style issues) which resulted in a box-shadow on mouse over (coming from the Kadence free theme). Had to write some CSS to remove this box-shadow.

**Fix**

We need to replace the `button` tag with a `div` tag with the following attributes `tabindex="0" role="button"` and add the necessary deprecation steps for it.

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3055

### CODE REVIEW

File: src/block/video-popup/deprecated.js [hunk 1]
```diff
@@ -2,12 +2,36 @@ import { Save } from './save'
...
+			</button>
+		)
+	}
+	return output
+} )
+
 const deprecated = [
+	{
+		attributes: attributes( '3.12.12' ),
+		save: withVersion( '3.12.12' )( Save ),
```
Comment (bfintal) [inline src/block/video-popup/deprecated.js]:
```suggestion
		attributes: attributes( '3.12.14' ),
		save: withVersion( '3.12.14' )( Save ),
```

File: src/block/video-popup/deprecated.js [hunk 2]
```diff
@@ -2,12 +2,36 @@ import { Save } from './save'
...
 
+/**
+ * WordPress dependencies
+ */
+import { InnerBlocks } from '@wordpress/block-editor'
+import { addFilter } from '@wordpress/hooks'
+import { __ } from '@wordpress/i18n'
+
+addFilter( 'stackable.video-popup.save.div.content', 'stackable/3.12.12', ( output, props, contentClassNames ) => {
+	if ( semverCompare( props.version, '<', '3.12.12' ) ) {
```
Comment (bfintal) [inline src/block/video-popup/deprecated.js]:
```suggestion
addFilter( 'stackable.video-popup.save.div.content', 'stackable/3.12.14', ( output, props, contentClassNames ) => {
	if ( semverCompare( props.version, '<', '3.12.14' ) ) {
```
