### PR TITLE
fix (progress-blocks): support commas when using dynamic fields as progress value

### LINKED ISSUE #2688: Progress blocks - Commas are not recognized along with the digits when adding in Progress input field or as a dynamic content data
**Describe the bug**
- Unable to recognize comma in numbers when adding it in:
   - Input field data
   - Dynamic Content data
- Applies to both Progress Bar & Progress Circle blocks
- Should apply to field such as:
   - Progress
   - Maximum Progress (to confirm) 

**To Reproduce**
1. Add a new page
2. Add any Progress block
3. Type "10,000" on Progress Input field (input) OR Get data from Dynamic Content with the text "10,000"
4. See if the Progress block reads it as a number

**Expected behavior**
Commas should be recognized along with the digits when adding in Progress input field or as a dynamic content data (e.g. if I put data as "10,000", it should recognize it as a number)

**Screenshots**

Input Field:
https://github.com/gambitph/Stackable/assets/103395655/837c7512-74a0-4dcf-8a09-b4d1b2a962df

Dynamic Content:

https://github.com/gambitph/Stackable/assets/103395655/eecae7b2-0923-4d90-8c4a-0f6011ef74fb

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2688

### CODE REVIEW

File: src/block-components/progress-bar/style.js [hunk 1]
```diff
@@ -30,6 +30,9 @@ const Styles = props => {
 				styleRule="--progress-value"
 				attrName="progressValue"
 				key="progressValue"
+				valueCallback={ value => {
+					return getDynamicContent( value ).replace( /,/g, '' )
+				} }
```
Comment (bfintal) [inline src/block-components/progress-bar/style.js:35]: Please add checks whether value is present first before you run it on `.replace`, this might produce an error if the value is not present or the value is invalid. `value` can also be undefined, try using `value || ''`

File: src/block/progress-bar/edit.js [hunk 2]
```diff
@@ -70,7 +70,7 @@ const Edit = props => {
 	} )
 
 	// parsing string to number since progress value is of a string type to support dynamic content
-	const parsedProgressValue = parseFloat( useDynamicContent( attributes.progressValue ) )
+	const parsedProgressValue = parseFloat( useDynamicContent( attributes.progressValue ).replace( /,/g, '' ) )
```
Comment (bfintal) [inline src/block/progress-bar/edit.js:73]: Please add checks here as well

File: src/block/progress-circle/edit.js [hunk 3]
```diff
@@ -66,7 +66,7 @@ const Edit = props => {
 	] )
 
 	// this is to handle dynamic content; only show valid value
-	const parsedProgressValue = parseFloat( useDynamicContent( attributes.progressValue ) )
+	const parsedProgressValue = parseFloat( useDynamicContent( attributes.progressValue ).replace( /,/g, '' ) )
```
Comment (bfintal) [inline src/block/progress-circle/edit.js:69]: Please add checks here as well

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/block/progress-bar/edit.js [hunk 4]
```diff
@@ -137,6 +139,9 @@ const Edit = props => {
 						</div>
 					</div>
 				</div>
+				<style>
+					{ `.editor-styles-wrapper .stk-${ props.attributes.uniqueId } .stk-progress-bar { --progress-value:${ derivedValue }% !important; }` }
+				</style>
```
Comment (bfintal) [inline src/block/progress-bar/edit.js:144]:
```suggestion
				{ /** Add our progress style here because we're adjusting the value using a hook */ }
				<style>
					{ `.editor-styles-wrapper .stk-${ props.attributes.uniqueId } .stk-progress-bar { --progress-value:${ derivedValue }% !important; }` }
				</style>
```

File: src/block/progress-circle/edit.js [hunk 5]
```diff
@@ -150,6 +152,9 @@ const Edit = props => {
 						) }
 					</div>
 				</div>
+				<style>
+					{ `.editor-styles-wrapper .stk-${ props.attributes.uniqueId } .stk-progress-circle { --progress-value:${ derivedValue } }` }
+				</style>
```
Comment (bfintal) [inline src/block/progress-circle/edit.js:157]:
```suggestion
				{ /* Add our progress style here because we're adjusting the value using a hook */ }
				<style>
					{ `.editor-styles-wrapper .stk-${ props.attributes.uniqueId } .stk-progress-circle { --progress-value:${ derivedValue } }` }
				</style>
```
