### PR TITLE
fix (map block): google maps js API callback warning

### LINKED ISSUE #2734: Map block - Console warning: Google Maps JavaScript API has been loaded directly without a callback
**Describe the bug**
When adding a Map block in the page, it shows a console warning:
Screenshot 2023-07-14 at 12 02 41 PM

**To Reproduce**
1. Add a new page
2. Add Map block
3. Save page and go to frontend
4. Open console
5. See warning

**Expected behavior**
Console warning mentioned above should not be present.

### PR DESCRIPTION
**Pull request by mxkae**
fixes #2734

### CODE REVIEW

File: src/block/map/frontend-map.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ class StackableMap {
 		return new Promise( resolve => {
 			const script = document.createElement( 'script' )
 			script.id = 'stackable-google-map'
-			script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places`
+			script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places&callback=Function.prototype`
```
Comment (bfintal) [inline src/block/map/frontend-map.js:29]:
```suggestion
			// Add callback to prevent warnings.
			script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places&callback=Function.prototype`
```

File: src/block/map/util.js [hunk 2]
```diff
@@ -106,7 +106,7 @@ const loadScriptAsync = apiKey => {
 		}
 		const script = document.createElement( 'script' )
 		script.id = 'stackable-google-map'
-		script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places`
+		script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places&callback=Function.prototype`
```
Comment (bfintal) [inline src/block/map/util.js:109]:
```suggestion
		// Add callback to prevent warnings.
		script.src = `https://maps.googleapis.com/maps/api/js?key=${ apiKey }&libraries=places&callback=Function.prototype`
```
