### PR TITLE
fix(text): force the replacement of parsed blocks for pasting serialized bl…

### LINKED ISSUE #3310: Posts block - Continue reading link translation issue
**Describe the bug**
- When deleting the free Stackable plugin in the website, the "Continue reading" link translates as English instead of the assigned site language (e.g. Italiano)
- Issue in both editor and frontend

**To Reproduce**
1. Activate Stackable Premium
2. Install Stackable Free (but do not activate yet)
3. Add a new page
4. Add a Posts block
5. Save page
6. Translated website to "Italian"
7. Go to the page from step 5
8. "Continue Reading" is translated as Italian (correct)
9. Deleted Stackable Free plugin
10. "Continue Reading" is translated as English (issue)

**Expected behavior**
- When using only Stackable Premium in a site, it should still translate the "Continue reading" link

**Screenshots**

https://github.com/user-attachments/assets/2da7a53b-8ce2-4949-a469-8dbf9c0eb9e4

### LINKED ISSUE #3330: When default text block is Stackable Text block, I'm unable to paste Text blocks properly
**Describe the bug**
- Related to this new feature: https://github.com/gambitph/Stackable/issues/3279
- It only copies the text content and not the whole text block
- Issue happens when trying to paste any text block on a Stackable Text block or a WordPress Paragraph block
- Text blocks such as:
   - Heading
   - Subtitle
   - Text
   - Icon List (becomes a normal Text block)
- Native WordPress text blocks and other third party block plugins are also affected
- Issue happens if this Stackable setting is enabled:
Screenshot 2024-09-27 at 8 38 02 AM

**To Reproduce**
1. Go to Stackable settings
2. Enable "Stackable Text as Default Block" setting
3. Add a new page
4. Add any text block (e.g. Heading)
5. Add any stylings
6. Copy block
7. Add a new Stackable Text block or Paragraph block
8. Paste the Heading block
9. See that it only pastes the text content

**Workaround**
- Turn off the default text block setting first when copying the blocks listed above

**Expected behavior**
- Should still be able to paste the whole block

**Screenshots**

https://github.com/user-attachments/assets/93912b82-dea6-49e8-b11f-24a2a33a319f

### PR DESCRIPTION
**Pull request by Arukuen**
…ocks

fixes #3330

### CODE REVIEW

File: src/block/text/util.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+import { useCallback } from '@wordpress/element'
+
+export const useOnPaste = clientId => {
+	const { replaceBlocks } = useDispatch( blockEditorStore )
+
+	return useCallback( event => {
+		event.preventDefault()
+		// Get the raw HTML from the clipboard
+		const html = event.clipboardData.getData( 'text/html' )
+		const plain = event.clipboardData.getData( 'text/plain' )
```
Comment (bfintal) [inline src/block/text/util.js]:
```suggestion
		const html = event.clipboardData?.getData( 'text/html' ) || ''
		const plain = event.clipboardData?.getData( 'text/plain' ) || ''
```
