### PR TITLE
fix: resetting on global typography should only affect the current de…

### LINKED ISSUE #3550: Global mobile typography setting displays reset button on desktop
**Describe the bug**
When a global typography style is configured specifically for mobile viewports, a reset button appears in the desktop view. When you click reset in desktop, it also resets the mobile values.

**To Reproduce**
1. Go to Stackable Settings > Global Typography Typescale
2. Change into Mobile view and select 1.25 Major Third typescale
3. Switch into desktop view
4. See error (reset button on the 

**Expected behavior**
When a global typography style is configured specifically for mobile view, the styling should apply only to mobile view. When the reset button is clicked within the desktop view, it should only reset the typography settings specific to the desktop view.

**Screenshots**

https://github.com/user-attachments/assets/f9446246-82fd-406f-9326-d78d0e992e9e

### PR DESCRIPTION
**Pull request by Arukuen**
…vice type

fixes #3550 

## Summary by CodeRabbit

* Improvements
  * Typography resets are now device-aware, preserving selector-specific styles while clearing size and spacing only for the current device.
  * Default font family is applied based on the active font pair during reset for more consistent results.
  * Detection of when a reset is needed now respects per-device values, reducing unnecessary changes.

* Bug Fixes
  * Resolves inconsistencies where typography resets could unintentionally affect other devices or overlook device-specific settings.

### CODE REVIEW

File: src/plugins/global-settings/typography/index.js [hunk 1]
```diff
@@ -350,11 +350,30 @@ addFilter( 'stackable.global-settings.inspector', 'stackable/global-typography',
...
+		const deviceFontSizeKey = getDevicePropertyKey( 'fontSize', deviceType )
+		const deviceFontSizeUnitKey = getDevicePropertyKey( 'fontSizeUnit', deviceType )
+		const deviceLineHeightKey = getDevicePropertyKey( 'lineHeight', deviceType )
+		const deviceLetterSpacingKey = getDevicePropertyKey( 'letterSpacing', deviceType )
+
+		newSettings = {
+			...typographySettings,
+			[ selector ]: {
+				...typographySettings[ selector ],
+				fontFamily: getDefaultFontFamily( selector ),
```
Comment (bfintal) [inline src/plugins/global-settings/typography/index.js:363]: Since this is a reset, shouldn't the fontFamily be blank?

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/plugins/global-settings/typography/index.js (hunk 1 above)
Comment (Arukuen) [reply src/plugins/global-settings/typography/index.js:363]: The default font family depends on the currently selected font pair, which will be provided by `getDefaultFontFamily`.
