### PR TITLE
fix: add admin notice if occurs error in settings

### LINKED ISSUE #2882: Plugin Settings: Display an error message if REST API fails
If the REST API doesn't work, or saving/loading settings in the plugin settings area doesn't work, we should display an **admin notice** with the message we got from the REST fetch request (if there is one) and a message to check the settings of any security plugin or security setting in their website that disables REST API for administrators.

Steps to replicate:
1. install https://wordpress.org/plugins/all-in-one-wp-security-and-firewall/ and enable Intranet option
2. Go to Stackable settings
3. See that all settings are not loading, you also cannot change settings

### PR DESCRIPTION
**Pull request by Arukuen**
fixes #2882
Screenshot 2024-06-27 223818

### CODE REVIEW

File: src/welcome/admin.js [hunk 1]
```diff
@@ -219,6 +219,31 @@ const pick = ( obj, keys ) => {
...
+	}, [] )
+
+	if ( ! error ) {
+		return null
+	}
+
+	return (
+		<div className="notice notice-error">
+			<p>{ __( 'Error getting Stackable settings. We got the following error. Please contact your administrator.', i18n ) }</p>
+			{ error.responseJSON.message && <p><strong>{ error.responseJSON.message }</strong></p> }
```
Comment (bfintal) [inline src/welcome/admin.js]: Please also add the error code. Afterwards please set for QA

**Review by bfintal — CHANGES_REQUESTED** [review]
