### PR TITLE
Fixes responsive preview mode for WP5.7

### LINKED ISSUE #1077: Opacity not working
The opacity for mobile mode is not working in Backend

1. Add an accordion block
2. Go to Advanced > General > Opacity
3. adjust the opacity in mobile viewport
4. see bug in Backend

see labels for the list of blocks with the same bug

### LINKED ISSUE #1078: General alignment not working
The general alignment on mobile mode is not working for some blocks (Backend)

1. add an accordion block
2. go to Style > General > Align
3. adjust the alignment in mobile viewport
4. see bug in Backend

see labels for list of blocks with the same bug

### PR DESCRIPTION
**Pull request by blankart**
FIxes #1077, fixes #1078

### CODE REVIEW

**Review by bfintal — CHANGES_REQUESTED** [review]
Maybe we can just use the following as the fix, then retain the other lines:
```
const query = '.editor-styles-wrapper' +
	', .edit-post-visual-editor' // Fallback for < WP 5.6
```

File: src/plugins/responsive-preview/index.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ import domReady from '@wordpress/dom-ready'
 import { addAction } from '@wordpress/hooks'
 import { select, subscribe } from '@wordpress/data'
 
-const query = '.edit-post-visual-editor'
+const query = '.editor-styles-wrapper'
```
Comment (bfintal) [inline src/plugins/responsive-preview/index.js:19]:
```suggestion
const query = '.edit-post-visual-editor > .editor-styles-wrapper' +
	', .edit-post-visual-editor.editor-styles-wrapper' // Fallback for < WP 5.6
```
