### PR TITLE
Blog posts include fix

### LINKED ISSUE #984: Assigning post ids in blog posts block ignores the number of items attributes
Steps to replicate:
1. Add a blog posts block
2. Enter 5 post ids in the posts settings area
3. Set the number of items to 4
4. More than 4 posts will show in the frontend

### PR DESCRIPTION
**Pull request by blankart**
Fixes #984

### CODE REVIEW

File: src/block/blog-posts/index.php [hunk 1]
```diff
@@ -140,6 +140,11 @@ function stackable_render_blog_posts_block( $attributes, $content ) {
 
 		$recent_posts = wp_get_recent_posts( $post_query );
 
+		// Manually slice the array based on the number of posts per page.
+		if ( sizeof( $recent_posts ) > $post_query['numberposts'] ) {
```
Comment (bfintal) [inline src/block/blog-posts/index.php:144]: Please use `count` instead of sizeof. Also, `wp_get_recent_posts` can return `false` if no posts are found, you'll need to check for this.

**Review by bfintal — CHANGES_REQUESTED** [review]
Please see changes

File: src/block/blog-posts/index.php [hunk 2]
```diff
@@ -140,6 +140,11 @@ function stackable_render_blog_posts_block( $attributes, $content ) {
 
 		$recent_posts = wp_get_recent_posts( $post_query );
 
+		// Manually slice the array based on the number of posts per page.
+		if ( is_array( $recent_posts ) && count( $recent_posts ) > $post_query['numberposts'] ) {
+			$recent_posts = array_slice( $recent_posts, 0, $post_query['numberposts'] );
+		}
+
```
Comment (bfintal) [inline src/block/blog-posts/index.php:147]:
```suggestion
		// Manually slice the array based on the number of posts per page.
		if ( is_array( $recent_posts ) && count( $recent_posts ) > (int) $post_query['numberposts'] ) {
			$recent_posts = array_slice( $recent_posts, 0, (int) $post_query['numberposts'] );
		}

```
