### PR TITLE
fix (lightbox): prevent lightbox from not working if "srcset" has a different variation

### LINKED ISSUE #2724: Lightbox is not working if WP Rocket's Lazy Loading feature is enabled
**Describe the bug**
After disabling the lazy loading, lightbox began working again.

**Expected behavior**
Lightbox should work whether WP Rocket's Lazy Loading is enabled or disabled.

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2724

### CODE REVIEW

File: src/lightbox/frontend-image-lightbox.js [hunk 1]
```diff
@@ -7,11 +7,12 @@ const getImageFromSrcset = el => {
...
-	const srcset = el.getAttribute( 'nitro-lazy-srcset' ) ||
-		// Support for Perfmatters lazy loading.
-		el.getAttribute( 'data-srcset' ) ||
-		el.getAttribute( 'srcset' )
+	// Search and return an attribute that ends with "srcset"
+	const srcsetName = el.getAttributeNames().find( v => {
+		return v.endsWith( 'srcset' )
+	} )
+
+	const srcset = el.getAttribute( srcsetName )
```
Comment (bfintal) [inline src/lightbox/frontend-image-lightbox.js:15]: Please try and use the exact `srcset` attribute first, and then if that's not available, resort to looking through the attribute names for a close match

**Review by bfintal — CHANGES_REQUESTED** [review]
