### PR TITLE
fix (color picker): shadow color and opacity

### LINKED ISSUE #3063: Color picker issue - Transparency selector in color picker RGBA/HSLA option not working
**Describe the bug**
**_Note: This issue is from the affiliate who encountered bugs when testing out Stackable_**

- This issue is visible for the **Advanced Shadow Options > Shadow Color**
- Issue happens whether typing or moving slider in the A (alpha)

**To Reproduce**
1. Add a new page
2. Add any block (e.g. Heading)
3. In Inspector go to Style > Borders & Shadows
4. In the Shadow / Outline, open "Advanced Shadow Options" by clicking the cog icon
5. Open Shadow Color
6. Change color format to RGB or HSL
7. Try typing in the A (alpha) field or moving the slider
8. See that it doesn't work

**Expected behavior**
Transparency selector should work for Shadow option (typing/moving slider)

**Screenshots**
- Only stays as 100 (slider) or goes back to 100 (typing)

https://github.com/gambitph/Stackable/assets/103395655/fc668ca2-c603-4ca0-98da-2f34732aebbd

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3063

### CODE REVIEW

File: src/block/blockquote/deprecated.js [hunk 1]
```diff
@@ -2,9 +2,31 @@ import { Save } from './save'
...
+
+			return hasBlockShadow || hasContainerShadow
+		},
+		migrate: attributes => {
+			let newAttributes = { ...attributes }
+
+			newAttributes = deprecateBlockShadowColor.migrate( newAttributes )
+			newAttributes = deprecateContainerShadowColor.migrate( newAttributes )
+
+			return newAttributes
```
Comment (bfintal) [inline src/block/blockquote/deprecated.js]: Add the other migration methods to this one just in case since the deprecations can still be affected
```suggestion
			let newAttributes = {
				...attributes,
				version: 2,
			}

			newAttributes = deprecateBlockShadowColor.migrate( newAttributes )
			newAttributes = deprecateContainerShadowColor.migrate( newAttributes )
			newAttributes = deprecateContainerBackgroundColorOpacity.migrate( newAttributes )
			newAttributes = deprecateBlockBackgroundColorOpacity.migrate( newAttributes )

			return newAttributes
```

Comment (bfintal) [reply src/block/blockquote/deprecated.js]: Also add the migration to the old deprecations:

```js
newAttributes = deprecateBlockShadowColor.migrate( newAttributes )
newAttributes = deprecateContainerShadowColor.migrate( newAttributes )
```

**Review by bfintal — CHANGES_REQUESTED** [review]
