### PR TITLE
fix: timeline lines on iOS devices

### LINKED ISSUE #2912: Timeline block issue on Safari - Timeline lines are already filled upon scrolling
**Describe the bug**
If you view the page https://crexcell-com.stackstaging.com/about-us/ on a desktop browser then the timeline colors change with scrolling (expected). This does not work when viewing the same page on the built in Safari browser on ipad or iphone.

Upon testing from our end and viewing on ipad and iphone, the timeline accent color is stuck and does not change while scrolling. in the user's page, the whole line is already filled with the accent color.

**To Reproduce**
1. Add a new page
2. Add Timeline blocks
3. Add an accent color for the timeline blocks
4. Save page
5. View frontend and try scrolling down
6. See that the timeline lines are already filled with the accent color

**Expected behavior**
- Timeline lines should only be filled with the accent color upon scrolling. See video below:

https://github.com/gambitph/Stackable/assets/103395655/3c26de8b-de35-42d4-99e7-33ad6f97463f

**Screenshots**
- As you can see in the video below, the timeline lines are already filled upon scrolling:

https://github.com/gambitph/Stackable/assets/103395655/fa0791fe-c4e3-4779-b981-61b793d5acee

**Smartphone (please complete the following information):**
 - Device: tried with iPhoneX, iPhone 12 Pro but _no specific device_
 - OS: _no specific OS_
 - Browser: Safari
 - Browser Version: _no specific version_

### PR DESCRIPTION
**Pull request by mxkae**
fixes #2912 

Timeline block uses `background-attachment: fixed` for the timeline lines' scrolling effect. However, it is currently not supported by iOS/iPadOS as discussed in this [thread](https://developer.apple.com/forums/thread/99883).

This fix now fills timeline lines (for iOS devices only) so that for pages with many consecutive timeline blocks it won't look broken like this:

https://github.com/gambitph/Stackable/assets/98727316/fce98493-2ba8-4127-97b5-5bc319584e20

Instead, it will now look like this:

https://github.com/gambitph/Stackable/assets/98727316/f9e1f3e7-7cc0-490d-adc3-bcfed9584b8a

### CODE REVIEW

**Comment by andeng1106** [comment]
@mxkae Remaining issue: Issue still exists on certain iPad devices.
Tested on:

Has issue:
- iPad Pro 4th Gen
image

- iPad 10th Gen

https://github.com/gambitph/Stackable/assets/103395655/d68c9c9c-870f-41ef-8419-e6524e1c8ef4


No issue:
- iPad Mini 6th Gen (assumption: it is ok because it's using mobile view)
Screenshot 2023-10-24 at 4 39 53 PM

File: src/block/timeline/index.php [hunk 1]
```diff
@@ -17,7 +17,9 @@ function stackable_load_timeline_ios_frontend_polyfill( $block_content, $block )
 
 	$user_agent = ! empty( $_SERVER['HTTP_USER_AGENT'] ) ? $_SERVER['HTTP_USER_AGENT'] : '';
 	// Add polyfill if device is iPhone/iPad
-	if ( ! empty( $user_agent ) && ( stripos( $user_agent, 'iPhone' ) !== false || stripos( $user_agent, 'iPad' ) !== false ) ) {
+	// Include Safari because by default the User Agent in Safari on iPadOS is same  on MacOS
+	// Reference: https://developer.apple.com/forums/thread/119186
+	if ( ! empty( $user_agent ) && ( stripos( $user_agent, 'iPhone' ) !== false || stripos( $user_agent, 'iPad' ) !== false || stripos( $user_agent, 'Safari/' ) !== false ) ) {
```
Comment (bfintal) [inline src/block/timeline/index.php:22]: Won't including Safari affect even MacOS Safari?

**Review by bfintal — CHANGES_REQUESTED** [review]
