### PR TITLE
Fix/accordion highlight

### LINKED ISSUE #3096: Accordion block - When expanding accordion, it gets highlighted on frontend
**Describe the bug**
- No certain option/setting where this can be disabled
- This issue happens if Accordion block is:
    - Outside Stackable Columns block
    - Inside Group/Columns block

https://github.com/gambitph/Stackable/assets/103395655/38847133-a4e6-4b2b-9694-0ea98e5bd953

- This issue causes the highlight in the Accordion (Shadow layout) to glitch if inside the Columns block

https://github.com/gambitph/Stackable/assets/103395655/4d2b0132-0ba0-4616-ab0e-b411428c01f7

### PR DESCRIPTION
**Pull request by Arukuen**
fixes #3096

- No outline when clicked, but outline when tabbed for accessibility

### CODE REVIEW

File: src/block/accordion/frontend-accordion.js [hunk 1]
```diff
@@ -30,6 +30,10 @@ class StackableAccordion {
 					el.doAnimate = false
 					const preHeight = el.dataset.preHeight
 
+					// Prevent text selection while animating
+					const content = el.querySelector( '.stk-block-accordion__content' )
+					content.style.userSelect = 'none'
```
Comment (bfintal) [inline src/block/accordion/frontend-accordion.js]: It seems that doing this on the content would still make the text highlight. I would recommend doing this on the element itself to prevent this:
```suggestion
					// Prevent text selection while animating
					el.style.userSelect = 'none'
```

File: src/block/accordion/frontend-accordion.js [hunk 2]
```diff
@@ -51,6 +55,22 @@ class StackableAccordion {
...
+							// eslint-disable-next-line @wordpress/no-global-get-selection
+							const selection = window.getSelection()
+							if ( selection.removeAllRanges ) {
+								selection.removeAllRanges()
+							}
+						} else if ( document.selection ) {
+							// For older IE browsers
+							document.selection.empty()
+						}
+						content.style.userSelect = 'auto'
```
Comment (bfintal) [inline src/block/accordion/frontend-accordion.js]: I see that you are clearing the selection because the `userSelect` above was not taking full effect and you can still highlight text when opening an accordion. Applying the style directly on the element fixes things, and now you do not need all of the selection removal code.

Also, to me, if the fix only partially works and you needed to add some selection removal code to compensate is an indicator that there should be a cleaner solution 👍

```suggestion
						el.style.userSelect = 'auto'
```

**Review by bfintal — CHANGES_REQUESTED** [review]
Good solution, just a suggestion for improvement.
