### PR TITLE
fix: display set attribute as placeholder in range control for tablet/mobile

### LINKED ISSUE #2859: Display currently set attribute value in tablet and mobile
In inspector range controls, if there's a value set for a larger screen size, switching to a smaller screen size should show the inherited value as a placeholder. 

Scenario 1:
- Desktop value: `30`
- Tablet placeholder: `30` value: `''` 
- Mobile placeholder: `30` value: `''`

Scenario 2:
- Desktop value: ``
- Tablet placeholder: `` value: `30`
- Mobile placeholder: `30` value: ``

Scenario 3:
- Desktop placeholder: `12` value: `30`
- Tablet placeholder: `30` value: `50`
- Mobile placeholder: `50` value: ``

### PR DESCRIPTION
**Pull request by mxkae**
fixes #2859

### CODE REVIEW

File: src/components/four-range-control/index.js [hunk 1]
```diff
@@ -133,6 +148,45 @@ const FourRangeControl = memo( props => {
...
+		propsToPass.initialPositionTop = unit === _unit ? _value?.top : ''
+		propsToPass.placeholderTop = unit === _unit ? _value?.top : ''
+		propsToPass.initialPositionLeft = unit === _unit ? _value?.left : ''
+		propsToPass.placeholderLeft = unit === _unit ? _value?.left : ''
+		if ( setAll ) {
+			propsToPass.initialPositionRight = unit === _unit ? _value?.right : ''
+			propsToPass.placeholderRight = unit === _unit ? _value?.right : ''
+			propsToPass.initialPositionBottom = unit === _unit ? _value?.bottom : ''
+			propsToPass.placeholderBottom = unit === _unit ? _value?.bottom : ''
+		}
```
Comment (bfintal) [inline src/components/four-range-control/index.js:161]: `setAll` looks wrong.. because there are various props that can make the four range control show different sets of range controls.

**Review by bfintal — CHANGES_REQUESTED** [review]
1. Can you extend this to also support hover states:

- Hover state in tablet/mobile should show parent hovered, if present, if not then use normal state
- Parent hovered in tablet/mobile should show normal state

2. Please clean up commented code
3. I feel that the four range control implementation needs some refinement or refactoring.

I think the placeholders can be computed in a simpler way than adding them in `propsToPass`

If you check the different `RangeControl` components used, you'll see that the values are done like this: `value={ firstValue }`. You can try computing for the placeholder for this `firstValue` then use that whenever that value is used.

**Comment by andeng1106** [comment]
**Issues:**

- [ ] Margin has a default placeholder of -200 on all sides on Tablet & Mobile

https://github.com/gambitph/Stackable/assets/103395655/0284a3f6-3545-47fa-9492-8826c6524930


- [ ] Position has a default placeholder of `-100` on all sides on Tablet & Mobile

https://github.com/gambitph/Stackable/assets/103395655/d99d5386-6eeb-4e8c-80f1-19cadcdbe518


- [ ] Paddings has a default placeholder of `0` on all sides on Tablet & Mobile and all hover states

https://github.com/gambitph/Stackable/assets/103395655/a8e0ec6f-193e-417c-88e0-a968a2a8181d


- [ ] Borders & Shadows > Shadow / Outline has a default placeholder of `0` on mobile and normal state only

https://github.com/gambitph/Stackable/assets/103395655/f1e433c6-e3f6-4cc6-8399-dbdd998f353d


- [ ] Button Paddings has a default placeholder of `-Infinity` on all sides on Tablet & Mobile

https://github.com/gambitph/Stackable/assets/103395655/8078d7ee-9dff-4180-9a44-f7850116ef0f




**Clarifications:**
Scenario 1 - Hover:
I applied settings in Hovered states for Desktop view:
    - Normal - `40`
    - Hovered state - `30`
    - Parent Hovered state - `78`
    - Collapsed state (Accordion) - `149`
But upon switching to Tablet & Mobile view it displays:
    - Normal - `40`
    - Hovered state - `40`
    - Parent Hovered State - `40`
    - Collapsed state (Accordion) - `40`


Scenario 2 - Hover:
I didn't apply Normal state setting:
    - Normal - `0`
    - Hovered state - `30`
    - Parent Hovered state - `78`
    - Collapsed state (Accordion) - `149`
But upon switching to Tablet/Mobile view it displays:
    - Normal - `''`
    - Hovered state - `''`
    - Parent Hovered State - `''`
    - Collapsed state (Accordion) - `''`

Questions/Notes:
- Are both Scenario 1 & 2 clarifications expected?
- Same thing happens for Tablet > Mobile


@mxkae @bfintal

**Comment by mxkae** [comment]
For now, I just set all hover states to have a default `''` placeholder, will create a new pr for hover states.
