### PR TITLE
WordPress 5.8 Bug Fixes

### LINKED ISSUE #1314: styles not reflecting in backend when adding a block as template
when you add a stackable block and edit it in the page template area, the adjustments for the block is not reflecting in backend. Only in frontend.

Steps:
1. Activate WP5.8 RC2
2. Add this inside the functions.php file of your active theme: `add_theme_support( 'block-templates' );`
3. Add a new post
4. click Post tab in the Inspector
5. under Template panel, click New
6. add an accordion block -> change the Title font family & color.
7. see bug in backend.

the styles correctly change in frontend.

Note: background images do not display in the backend.

backend:
Screen Shot 2021-07-12 at 3 27 38 PM

frontend:
Screen Shot 2021-07-12 at 3 28 24 PM

### LINKED ISSUE #1315: URL popover does not close when clicking outside of the block
When the page template is open, the url popover of stackable buttons does not close when clicking outside the block:

Steps:
Add this inside the functions.php file of your active theme: `add_theme_support( 'block-templates' );`
1. Add a new page
2. add a cta inside that page
3. click new template.
4. in the template view, click the button of cta. see bug.

see snippet here - 
https://user-images.githubusercontent.com/28699204/125249439-d1eafc80-e327-11eb-8022-910829775f35.mov

expected behavior:
https://user-images.githubusercontent.com/28699204/125249961-550c5280-e328-11eb-84c8-58a69459eada.mov

### LINKED ISSUE #1318: global typography does not apply to native blocks when a template is set for the page
Steps:
Add this inside the functions.php file of your active theme: `add_theme_support( 'block-templates' );`
1. in a new page, add a native paragraph & heading block
2. adjust the Stackable global typography for h2 & body text. Apply styles to `Stackable & native blocks only`
3. in the inspector Page options, click the Template panel > New > create
4. it will show the page template view. Publish and check frontend:
the global typography did not apply to these native blocks

### LINKED ISSUE #1319: Opening an accordion in the inspector closes the accordion in the widgets area
If you add any stackable block and click any accordion in the inspector options, the accordion of the widgets area closes too.

Steps:
1. Go to Appearance > Widgets
2. add any stackable block.
3. open any accordion under Style / Advanced tab.
4. see bug.

snippet:
https://user-images.githubusercontent.com/28699204/125570390-e2804644-1fac-43e7-b8ac-cac7870517cb.mov

the widgets accordion should not close.

### LINKED ISSUE #1320: Dynamic content & color highlight in toolbar has extra borders
Screen Shot 2021-07-14 at 2 10 40 PM

happens in WP 5.7.2

### PR DESCRIPTION
**Pull request by blankart**
Fixes #1314, fixes #1315, fixes #1318, fixes #1319, fixes #1320

### CODE REVIEW

File: src/plugins/global-settings/index.js [hunk 1]
```diff
@@ -35,6 +39,39 @@ addAction( 'stackable.global-settings.toggle-sidebar', 'toggle', () => {
...
 
 const GlobalSettings = () => {
+	const isEditingTemplate = useSelect( select => select( 'core/edit-post' ).isEditingTemplate() )
+
+	/**
+	 * WordPress 5.8 introduces block templates.
+	 *
+	 * When editing blocks inside a template window, the editor is mounted inside
+	 * an `iframe` DOMElement. For the styles to work, we need to mount the styles inside
+	 * the iframe document.
```
Comment (bfintal) [inline src/plugins/global-settings/index.js:49]:
```suggestion
	 * Render the global colors and typography in Gutenberg
	 *
	 * WordPress 5.8 introduces block templates.
	 * When editing blocks inside a template window, the editor is mounted inside
	 * an `iframe` DOMElement. For the styles to work, we need to mount the styles inside
	 * the iframe document.
```

File: src/plugins/global-settings/index.js [hunk 2]
```diff
@@ -35,6 +39,40 @@ addAction( 'stackable.global-settings.toggle-sidebar', 'toggle', () => {
...
+	 * WordPress 5.8 introduces block templates.
+	 * When editing blocks inside a template window, the editor is mounted inside
+	 * an `iframe` DOMElement. For the styles to work, we need to mount the styles inside
+	 * the iframe document.
+	 *
+	 * @since 2.17.2
+	 */
+	useEffect( () => {
+		const selector = isEditingTemplate ?
+			document.querySelector( 'iframe[title="Editor canvas"]' ).contentWindow.document.body :
```
Comment (bfintal) [inline src/plugins/global-settings/index.js:56]: This might fail if the string is translated to other languages. Try the other attribute:

```suggestion
			document.querySelector( 'iframe[name="editor-canvas"]' ).contentWindow.document.body :
```
