### PR TITLE
Container padding fix

### LINKED ISSUE #1217: Block paddings for tablet are capping at 30

### PR DESCRIPTION
**Pull request by blankart**
Fixes #1217

### CODE REVIEW

**Review by bfintal — CHANGES_REQUESTED** [review]
I don't think you need to specify the `sliderMin` and `sliderMax` values here. From what I know the range control should be able to handle things as expected if the `sliderMin` and `sliderMax` values are not provided.

File: src/components/column-padding-control/index.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ const ColumnPaddingControl = props => {
 			className="ugb--help-tip-advanced-column-paddings"
 			defaultLocked={ true }
 			min={ [ 0, 0, 0 ] }
-			max={ [ 500, 30, 100 ] }
+			sliderMax={ [ 500, 100, 100 ] }
```
Comment (bfintal) [inline src/components/column-padding-control/index.js:51]: Aside from this, are there other low tablet values which are clamped lower than mobile? it may be a good time to increase those if there are any.

File: src/components/spacing-control/index.js [hunk 2]
```diff
@@ -20,6 +20,8 @@ const SpacingControl = props => {
 	// Allow different sets of min/max/step values per screen size.
 	const min = Array.isArray( props.min ) ? props.min : [ props.min, props.min, props.min ]
 	const max = Array.isArray( props.max ) ? props.max : [ props.max, props.max, props.max ]
+	const sliderMin = Array.isArray( props.sliderMin ) ? props.sliderMin : [ props.sliderMin, props.sliderMin, props.sliderMin ]
```
Comment (bfintal) [inline src/components/spacing-control/index.js:23]: I don't think you need to specify the `sliderMin` and `sliderMax` values here. From what I know the range control should be able to handle things as expected if the `sliderMin` and `sliderMax` values are not provided.

Comment (blankart) [reply src/components/spacing-control/index.js:23]: We need to add this in order to pass the corresponding`sliderMin` and`sliderMax` value inside the `FourRangeControl` component

Comment (blankart) [reply src/components/spacing-control/index.js:23]: Additional note: Similar to `min` and `max`, `sliderMin` and `sliderMax` also handle number values `e.g. sliderMax={ 100 }`
