### PR TITLE
fix (compatibility): Core Framework inspector panels now open in Stackable blocks.

### LINKED ISSUE #3029: Unable to expand panels on Core Framework for Stackable blocks
**Describe the bug**
- Unable to open/expand the Core Framework panels for Stackable block's inspector settings
- Issue happens for Stackable blocks but okay with native wordpress blocks

**To Reproduce**
1. Install and activate Core Framework plugin (https://coreframework.com/)
2. In Core Framework settings, go to **Addons** and enable **Gutenberg**
3. Add a new page
4. Add a Stackable block (e.g. Heading)
5. Go to Inspector
6. Open the Core Framework panel
7. Try clicking the panels inside (e.g. try opening **Backgrounds**)
8. See that the Core Framework panel collapses (issue)
9. Add a native wordpress Heading block
10. Repeat steps 6-7
11. See that the **Backgrounds** panel expanded (expected)

**Expected behavior**
- Core Framework panels should expand upon clicking

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/b706d7d5-6600-4e50-b4d5-e12a9468f8ef

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #3029

### CODE REVIEW

File: src/components/panel-tabs/index.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ const TABS = [
 const DEFAULT_TABS = [ 'layout', 'style', 'advanced' ]
 
 export const closeAllOpenPanels = clickedEl => {
-	[].forEach.call( document.querySelector( '.edit-post-sidebar, .edit-widgets-sidebar, .block-editor-block-inspector' )?.querySelectorAll( '.components-panel__body .components-panel__body-toggle' ) || [], el => {
+	[].forEach.call( document.querySelector( '.edit-post-sidebar, .edit-widgets-sidebar, .block-editor-block-inspector' )?.querySelectorAll( '.components-panel__body .components-panel__body-toggle .stk-panel' ) || [], el => {
```
Comment (bfintal) [inline src/components/panel-tabs/index.js]: Is this correct? The component `Button` now has both classes: `components-panel__body-toggle stk-panel`, but the selector is a child selector? `.components-panel__body-toggle .stk-panel` (there's a space?)

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/components/panel-tabs/index.js (hunk 1 above)
Comment (prconcepcion) [reply src/components/panel-tabs/index.js]: That's a mistake. I will fix that.
