### PR TITLE
fix: button popover won't close. fixes #2032

### LINKED ISSUE #2032: Button link popover not closing when clicking outside the button
**To Reproduce**
1. Add a button block
2. add button text
3. click the button text to open Link popover
4. click outside the button to close Link popover - does not close

https://user-images.githubusercontent.com/28699204/142375597-7ad71072-b167-4789-8162-fecbe8cfcb4a.mov

**Expected behavior**
popover should close when clicking outside the button

### PR DESCRIPTION
**Pull request by bfintal**

### CODE REVIEW

File: src/block-components/icon/index.js [hunk 1]
```diff
@@ -61,25 +61,37 @@ export const Icon = props => {
...
+		}
+	}, [ isSelected, isOpen ] )
 
 	// Assign the outside click listener.
 	useEffect( () => {
 		document.body.addEventListener( 'click', clickOutsideListener )
-		return () => document.body.removeEventListener( 'click', clickOutsideListener )
+		return () => {
+			document.body.removeEventListener( 'click', clickOutsideListener )
+		}
```
Comment (bfintal) [inline src/block-components/icon/index.js:92]:
```suggestion
		return () => document.body.removeEventListener( 'click', clickOutsideListener )
```

File: src/block-components/link/index.js [hunk 2]
```diff
@@ -48,18 +48,31 @@ export const Link = props => {
...
-	}, [ popoverEl.current ] )
+	}, [ popoverEl.current, isOpen ] )
 
 	// Assign the outside click listener.
 	useEffect( () => {
 		document.body.addEventListener( 'click', clickOutsideListener )
-		return () => document.body.removeEventListener( 'click', clickOutsideListener )
+		return () => {
+			document.body.removeEventListener( 'click', clickOutsideListener )
+		}
```
Comment (bfintal) [inline src/block-components/link/index.js:75]:
```suggestion
		return () => document.body.removeEventListener( 'click', clickOutsideListener )
```
