### PR TITLE
fix (accordion): collapsed settings are now properly applied

### LINKED ISSUE #2723: Accordion block - Colors not working for Collapsed state in Accordion
**Describe the bug**
When adding colors in Collapsed state for Accordion block, it's not working for both editor and frontend

**To Reproduce**
1. Add a new page
2. Add an Accordion block
3. Try out the scenarios below (Screenshots part)
4. Make sure to check both frontend and editor
5. See issues

**Expected behavior**
Collapsed state color should work for all blocks in Accordion

**Screenshots**
Some scenarios in the video:
1. Added Collapsed state color for Icon Label's Heading & Icon - not working for both frontend and editor
7. Added Collapsed state color for Inner Column 2's Text block - working
8. Added an Image block inside Inner Column 2 and added overlay color - not working properly for both frontend and editor, might have a conflict with hover state color

https://github.com/gambitph/Stackable/assets/103395655/a5239e99-00c8-46db-9ab7-a3d31d032cfd

### PR DESCRIPTION
**Pull request by prconcepcion**
fixes #2723

### CODE REVIEW

File: src/components/block-css/index.js [hunk 1]
```diff
@@ -292,9 +292,9 @@ const BlockCss = props => {
 	// TODO: why do we have this condition for the collapsedSelector, but they just do the same prepending??
 	if ( hasCollapsed ) {
 		if ( blockState === 'collapsed' ) {
```
Comment (prconcepcion) [inline src/components/block-css/index.js:294]: It also goes in here when you click on the inner column when the accordion is open @bfintal

Comment (bfintal) [reply src/components/block-css/index.js:294]: I think that's expected because this is called during style generation, the collapsed styles are always generated regardless whether the accordion is collapsed or not
