### PR TITLE
Global Settings

### LINKED ISSUE #872: block color opacity option in the Global Color Palette does not work
changing the block color opacity does not do anything
ezgif-2-6e53aa69b97c

ezgif-2-df7e04144c6b

### LINKED ISSUE #873: hovering on a single color on  the  global color palette shows the color name instead of the Style Name
hovering on a single color on  the  global color palette shows the color name instead of the Style Name

image
image

### PR DESCRIPTION
**Pull request by blankart**
Fixes #872 
Fixes #873

### CODE REVIEW

File: src/plugins/global-settings/components/global-settings-color-picker/index.js [hunk 1]
```diff
@@ -0,0 +1,236 @@
...
+	}
+
+	const AddIcon = props => (
+		<Button
+			{ ...props }
+			isDefault
+			className="ugb-global-settings-color-picker__add-icon"
+			label="Add New Color"
+			icon={
+				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 190">
```
Comment (bfintal) [inline src/plugins/global-settings/components/global-settings-color-picker/index.js:125]: you should be able to use the built-in icons here `icon="plus"` or `plus-alt`

File: src/plugins/global-settings/global-colors/index.js [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+import { __ } from '@wordpress/i18n'
+import domReady from '@wordpress/dom-ready'
+import { loadPromise, models } from '@wordpress/api'
+import { dispatch, select } from '@wordpress/data'
+
+addFilter( 'stackable.global-settings.inspector', 'global-settings/global-colors', output => {
+	return (
+		<Fragment>
+			{ output }
+			<GlobalSettingsPanel
```
Comment (bfintal) [inline src/plugins/global-settings/global-colors/index.js:28]: Please use `PanelAdvancedSettings` instead. Check for existing components first before creating one. We have a lot of components and utility functions.

File: src/plugins/global-settings/components/global-settings-panel/index.js [hunk 3]
```diff
@@ -0,0 +1,33 @@
+/**
```
Comment (bfintal) [inline src/plugins/global-settings/components/global-settings-panel/index.js:1]: You can delete this in favor of using `PanelAdvancedSettings`

File: src/plugins/global-settings/components/global-settings-color-picker/index.js [hunk 4]
```diff
@@ -0,0 +1,236 @@
...
+// Component used to add a Delete Style button at the bottom of the COlorPicker.
+const DeleteButton = props => (
+	<div className="ugb-global-settings-color-picker__text-name components-color-picker__body">
+		<div className="components-color-picker__controls">
+			<Button
+				className="ugb-global-settings-color-picker__delete-button"
+				isLink
+				onClick={ props.onClick }
+			>
+				Delete Style
```
Comment (bfintal) [inline src/plugins/global-settings/components/global-settings-color-picker/index.js:55]: Please make sure the strings you use are translatable.

```suggestion
				{ __( 'Delete Style', i18n ) }
```

File: src/plugins/global-settings/components/global-settings-color-picker/index.js (hunk 1 above)
Comment (blankart) [reply src/plugins/global-settings/components/global-settings-color-picker/index.js:125]: I am using the icon list thin plus icon here. The ```plus``` icon has thick lines.

File: src/block/icon-list/edit.js [hunk 5]
```diff
@@ -243,12 +241,12 @@ const Edit = props => {
 
 		// Different icon sizes per device preview.
 		const { __experimentalGetPreviewDeviceType: getPreviewDeviceType } = select( 'core/edit-post' )
-		const previewDeviceType = getPreviewDeviceType()
+		const previewDeviceType = getPreviewDeviceType && getPreviewDeviceType()
```
Comment (bfintal) [inline src/block/icon-list/edit.js:244]: Instead of adding more checks, might be better to just assign it to `Desktop`
```suggestion
		const previewDeviceType = getPreviewDeviceType ? getPreviewDeviceType() : 'Desktop'
```

File: src/block/icon-list/edit.js [hunk 6]
```diff
@@ -243,12 +241,12 @@ const Edit = props => {
...
 		const currentIconSize = (
-			previewDeviceType === 'Desktop' ? props.attributes.iconSize :
+			previewDeviceType && ( previewDeviceType === 'Desktop' ? props.attributes.iconSize :
 				previewDeviceType === 'Tablet' ? ( props.attributes.iconTabletSize || props.attributes.iconSize ) :
-					( props.attributes.iconMobileSize || props.attributes.iconTabletSize || props.attributes.iconSize )
-		) || 20
+					( props.attributes.iconMobileSize || props.attributes.iconTabletSize || props.attributes.iconSize ) )
+		) || props.attributes.iconSize || 20
```
Comment (bfintal) [inline src/block/icon-list/edit.js:249]: In connection with above, you can remove the check for `previewDeviceType` since it's now assigned as `Desktop` if the function is not available

File: src/util/index.js [hunk 7]
```diff
@@ -129,17 +129,28 @@ export const descriptionPlaceholder = length => {
  */
 export const hexToRgba = ( hexColor, opacity = null ) => {
```
Comment (bfintal) [inline src/util/index.js:130]: These code should not be placed here. The `hexToRgba` function should only do one thing, convert hex to rgba. It shouldn't perform any global color functionality. Keep the global color functionality in the global color area

File: src/util/styles/index.js [hunk 8]
```diff
@@ -3,14 +3,28 @@
...
 import { default as _isDarkColor } from 'is-dark-color'
 import { lowerFirst, clamp } from 'lodash'
+import rgba from 'color-rgba'
 
 /**
  * WordPress dependencies
  */
 import { sprintf } from '@wordpress/i18n'
 
 export const isDarkColor = color => {
```
Comment (bfintal) [inline src/util/styles/index.js:13]: As with the `hexToRgba` function, the `isDarkColor` function should only perform checking whether the color is dark. Please keep all global color functions in the global color area.

File: src/plugins/global-settings/colors/index.js [hunk 9]
```diff
@@ -0,0 +1,360 @@
...
+addFilter( 'stackable.global-settings.inspector', 'global-settings/global-colors', output => {
+	const [ isPanelOpen, setIsPanelOpen ] = useState( true )
+	const [ disableReset, setDisableReset ] = useState( true )
+
+	// We make sure that we are getting the latest state for default colors.
+	const { defaultColors } = useSelect( select => select( 'core/block-editor' ).getSettings() )
+
+	const handleToggle = () => {
+		setIsPanelOpen( toggle => ! toggle )
+	}
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:45]: The `PanelAdvancedSettings` Component already has open and close functionality built-in, you don't need to handle toggling.

File: src/plugins/global-settings/colors/index.js [hunk 10]
```diff
@@ -0,0 +1,360 @@
...
+	}, [ defaultColors ] )
+
+	return (
+		<Fragment>
+			{ output }
+			<PanelAdvancedSettings
+				title={ __( 'Global Color Palette', i18n ) }
+				initialOpen={ true }
+				opened={ isPanelOpen }
+				onToggle={ handleToggle }
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:69]: The `PanelAdvancedSettings` Component already has open and close functionality built-in, you don't need to handle toggling.

File: src/plugins/global-settings/colors/index.js [hunk 11]
```diff
@@ -0,0 +1,360 @@
...
+import { __ } from '@wordpress/i18n'
+import domReady from '@wordpress/dom-ready'
+import { loadPromise, models } from '@wordpress/api'
+import {
+	dispatch, useSelect, select,
+} from '@wordpress/data'
+
+addFilter( 'stackable.global-settings.inspector', 'global-settings/global-colors', output => {
+	const [ isPanelOpen, setIsPanelOpen ] = useState( true )
+	const [ disableReset, setDisableReset ] = useState( true )
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:38]: Initial state of disabling should be false, so if something wrong happened, the user shouldn't be able to reset the colors

File: src/plugins/global-settings/colors/index.js [hunk 12]
```diff
@@ -0,0 +1,360 @@
...
+			// Update the block attributes.
+			if ( ! isEqual( updatedAttributes, block.attributes ) ) {
+				updateBlockAttributes( clientId, updatedAttributes )
+			}
+		}
+	} )
+} )
+
+domReady( () => {
+	// Mount a style in the document
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:329]: Please separate into another JS file the editor styling logic, similar to the global typography `editor-loader.js`

File: src/plugins/global-settings/colors/index.js [hunk 13]
```diff
@@ -0,0 +1,360 @@
...
+	const globalStyleEl = document.createElement( 'style' )
+	globalStyleEl.setAttribute( 'id', 'stackable-global-colors' )
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:331]: Instead of creating an element and querying it via id, make this into a Component instead. Please check the `editor-loader.js` in global typography for an example.

File: src/plugins/global-settings/colors/index.js [hunk 14]
```diff
@@ -0,0 +1,360 @@
...
+				} else {
+					dispatch( 'core/block-editor' ).updateSettings( {
+						colors: globalColors,
+						defaultColors: colors,
+					} )
+					doAction( 'stackable.global-settings.global-styles', globalColors )
+				}
+			} else {
+				updateToStackableGlobalColors()
+			}
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:357]:
```js
if ( ! Array.isArray( globalColors ) || ! globalColors.length ) { 
    updateToStackableGlobalColors()
} else {
    // dispatch...
}
```

File: src/plugins/global-settings/colors/index.js [hunk 15]
```diff
@@ -0,0 +1,360 @@
...
+			if ( Array.isArray( defaultColors ) && Array.isArray( colors ) ) {
+				// Get only the slug and colors.
+				const compareDefaultColors = defaultColors.map( defaultColor => ( { color: defaultColor.color, slug: defaultColor.slug } ) )
+				const compareColors = colors.map( color => ( { color: color.fallback || color.color, slug: color.slug } ) )
+				if ( ! isEqual( compareDefaultColors, compareColors ) ) {
+					setDisableReset( false )
+				}
+			}
+		}
+	}, [ defaultColors ] )
```
Comment (bfintal) [inline src/plugins/global-settings/colors/index.js:60]: Maybe it's better if you move this disableReset inside your `ColorPickers` component since the disableReset is mostly just passed around until it reaches the `ColorPickers`

File: src/plugins/global-settings/colors/readme.md [hunk 16]
```diff
@@ -0,0 +1,73 @@
...
+            name: 'Stackable Global Color 1',
+            slug: 'stk-global-color-2532351235',
+            color: 'var(--stk-global-color-aeb2rd, #ffffff)',
+            colorVar: '--stk-global-color-aeb2rd',
+            fallback: '#ffffff',
+            rgb: '255, 255, 255',
+        } 
+    ]
+
+doAction( 'stackable-global-settings.global-styles', colors )
```
Comment (bfintal) [inline src/plugins/global-settings/colors/readme.md:24]: Where is `stackable-global-settings.global-styles` used?

Comment (blankart) [reply src/plugins/global-settings/colors/readme.md:24]: It is used in the ColorPicker component.

File: src/block/icon-list/edit.js [hunk 17]
```diff
@@ -60,16 +60,12 @@ const includeEditorContentAlignClassName = attributes => {
...
-					mobileContentAlign
-		) || 'left'
+	const previewDeviceType = getPreviewDeviceType ? getPreviewDeviceType() : 'Desktop'
+	const alignment = (
+		previewDeviceType === 'Desktop' ? contentAlign : previewDeviceType === 'Tablet' ? tabletContentAlign : mobileContentAlign
+	) || 'left'
 
-		addedAlignmentClass[ `ugb-icon-list__${ alignment }-align` ] = alignment
-	}
+	addedAlignmentClass[ `ugb-icon-list__${ alignment }-align` ] = alignment
```
Comment (bfintal) [inline src/block/icon-list/edit.js:68]: Please move all the WP 5.4 `getPreviewDeviceType` compatibility to another PR so we can have the global settings PR only about global settings

File: src/block/icon-list/edit.js [hunk 18]
```diff
@@ -243,12 +239,12 @@ const Edit = props => {
...
 		const { __experimentalGetPreviewDeviceType: getPreviewDeviceType } = select( 'core/edit-post' )
-		const previewDeviceType = getPreviewDeviceType()
+		const previewDeviceType = getPreviewDeviceType ? getPreviewDeviceType() : 'Desktop'
 		const currentIconSize = (
 			previewDeviceType === 'Desktop' ? props.attributes.iconSize :
 				previewDeviceType === 'Tablet' ? ( props.attributes.iconTabletSize || props.attributes.iconSize ) :
-					( props.attributes.iconMobileSize || props.attributes.iconTabletSize || props.attributes.iconSize )
-		) || 20
+					( props.attributes.iconMobileSize || props.attributes.iconTabletSize || props.attributes.iconSize ) ) ||
+		 20
```
Comment (bfintal) [inline src/block/icon-list/edit.js:247]: Please move all the WP 5.4 `getPreviewDeviceType` compatibility to another PR so we can have the global settings PR only about global settings

File: src/plugins/global-settings/components/global-settings-color-picker/index.js [hunk 19]
```diff
@@ -0,0 +1,472 @@
+/**
```
Comment (bfintal) [inline src/plugins/global-settings/components/global-settings-color-picker/index.js:1]: Please move this file into it's own file in `plugins/global-settings/colors/color-picker.js` instead of a new folder inside `plugins/global-settings`

**Review by bfintal — APPROVED** [review]
