### PR TITLE
Mobile responsiveness fix

### LINKED ISSUE #766: display issue when you reset some options
on WP5.4, when you reset Min. Block Height, Max. Content Width, Block Margins, Block Paddings, and Column Paddings, the value will be blank:
ezgif-6-75da2a0b8fed

on WP5.5, when you reset these options, the value on the display will retain:
ezgif-6-f2a48e0e2dfa

### LINKED ISSUE #787: Min. Column Height has blank as default values
Min. Column Height has blank as default values
image

### LINKED ISSUE #799: Some blocks encountered an error when you add them in the block editor
Even if you didn't change or edit anything, some blocks will error out just by adding them to the block editor. 

ezgif-7-536bff2116d9

I'm using the **Version 2.9.0-responsive-fix-v3 plugin**.

These are the blocks that error out by adding them in the block editor:
- [ ] Feature
- [ ] Pricing Box
- [ ] Team Member
- [ ] Testimonial

If you have one of these blocks in your page, after you update/save then refresh your page, your page will be blank.
ezgif-7-3f81c838cc10

### LINKED ISSUE #802: Some font sizes, didn't change to Font Size Max=50px
- [ ] Button 1 and Button 2 in the Button Block, didn't change to Font Size Max=50px

image

image

- [ ] Number in the Number Box Block, didn't change to Font Size Max = 50px
image

### LINKED ISSUE #803: The default value of Separator Height got overridden
The default value of Separator Height (on mobile/tablet) got overridden when you added a custom value for desktop.

This only happens in the Separator Block, not on Top and Bottom Separator.

image

### LINKED ISSUE #804: CSS code for Margin Top and Bottom didn't apply
CSS code for Margin Top and Bottom didn't apply, I think the PX is missing:

image

### LINKED ISSUE #805: CSS code for Padding Top and Bottom didn't apply
CSS code for Margin Top and Bottom didn't apply, I think the PX is missing:

chrome_2oJQN2t0tT

### LINKED ISSUE #828: Force Square Image is not working
on 2.9.1:
ezgif-7-348f64ad7c4a

on Version 2.10.0-responsive-fix-v6:
ezgif-7-1e5920fe9a83

### LINKED ISSUE #829: The Number isn't centered on Mobile and Tablet when you change the Shape Size into a higher value
This is happening on Backend and Frontend.

On Desktop Preview Mode:
image

On Tablet Preview Mode:
image

On Mobile Preview Mode:
image

### LINKED ISSUE #830: The max value of Image Height was also set on Desktop mode
The Image Height (max: 300) on Card Block should only be set on Tablet and Mobile.

On 2.9.1:
ezgif-7-87d97e3da98a

On Version 2.10.0-responsive-fix-v6:
ezgif-7-1d6b309a5b1f

### LINKED ISSUE #831: Image Width is not working
Image Width is not working on Pricing Box Block and Feature Block

On 2.9.1:
ezgif-7-eeb68c956a64

On Version 2.10.0-responsive-fix-v6 :
ezgif-7-6b8ec40c848c

### LINKED ISSUE #832: When you set a value of Image Width on Tablet, it will also be applied to Mobile. This only happens on Testimonial Block.
This only happens on Testimonial Block.

ezgif-7-6eca06df0117

### PR DESCRIPTION
**Pull request by blankart**
### Ideal behavior

- [x] All Desktop range controls should have a value. In special cases, default value can be `blank`
- [x] Tablet and mobile range controls should be blank to show that they're assigned default values 
- [x] Using `0` (zero) as a value in range controls should assign the value `0` (zero) and not `default`

### Issues need to fix:
- [x] Some font sizes, didn't change to Font Size Max=50px #802
- [x] The default value of Separator Height got overridden #803
- [x] CSS code for Margin Top and Bottom didn't apply #804
- [x] CSS code for Padding Top and Bottom didn't apply #805
- [x] Force Square Image is not working #828
- [x] The max value of Image Height was also set on Desktop mode #830
- [x] The Number isn't centered on Mobile and Tablet when you change the Shape Size into a higher value #829
- [x] When you set a value of Image Width on Tablet, it will also be applied to Mobile. This only happens on Testimonial Block. #832
### Common Settings

- [x] Font size (max: 50)
- [x] Separator - Height
- [x] Min. Block Height
- [x] Max. Content Width
- [x] Block Margins - left and right
- [x] Block Margins - top and bottom (max: 100)
- [x] Block Paddings
- [x] Min, Column Height
- [x] Content Vertical Align
- [x] Column Paddings - left and right
- [x] Column Paddings - top and bottom (max: 100)

### Feature

- [x] Image Column Width
- [x] Image Width
- [x] Container Offset

### Container

- [x] Content Width
- [x] Image Height

### Count Up

- [x] Icon Size (max: 200)

### Number Box

- [x] Shape Size

### Card

- [x] Image Height (max: 300)

### Image Box

- [x] Image Height (max: 300)
- [x] Arrow Size

### Spacer

- [x] Height

### Pricing Box

- [x] Image Width

### Team Member

- [x] Image Width

### Testimonial

- [x] Image Width

### Notification

- [x] Dismissible - Icon Size

## Ideal behavior for all our range controls:

- [x] There should be no blank values.
- [x] Should work in WP 5.4
- [x] Should work in WP 5.5
- [x] If you click on reset, it should reset the value to the default
- [x] If you delete the value (make it blank), it should reset the value to the default
- [x] If you put `0`, the value should be `0` and not revert to the default value
- [x] Default values should show a number (not blank). If a padding is 10px by default, the value should show `10`
- [x] Desktop values should show as the default value for tablet and mobile; tablet values should show as defaults for mobile

Fixes #766, fixes #787, fixes #802, fixes #803, fixes #804, fixes #799, fixes #805, fixes #828, fixes #830, fixes #831, fixes #832, fixes #828, fixes #829

### CODE REVIEW

**Comment by blankart** [comment]
Fixes #787

File: src/block/card/style.js [hunk 1]
```diff
@@ -78,7 +82,21 @@ export const createStyles = props => {
 		...createImageBackgroundStyleSet( 'image%s', 'ugb-card__image', props.attributes ),
 	} )
 	if ( show.imageHeight ) {
-		styles.push( ...createResponsiveStyles( '.ugb-card__image', 'imageBackground%sHeight', 'height', '%spx', props.attributes, true ) )
+		styles.push( {
```
Comment (bfintal) [inline src/block/card/style.js:85]: Better to put the definition of `maxResponsiveSize` here so that it's near the area where it will be used

File: src/block/team-member/style.js [hunk 2]
```diff
@@ -68,9 +68,24 @@ export const createStyles = props => {
...
-			...createImageStyleSet( 'image%s', 'ugb-img', props.attributes ),
+			...createImageStyleSetDesktopOnly( 'image%s', 'ugb-img', props.attributes ),
+		} )
+
+		styles.push( {
+			desktopOnly: {
+				[ `.ugb-team-member__image` ]: {
+					width: appendImportant( getValue( 'imageWidth', '%spx' ) ),
+				},
+			}, tablet: {
```
Comment (bfintal) [inline src/block/team-member/style.js:79]: Instead of this:

```js
}, tablet: {
```

please follow this convention instead:

```js
},
tablet: {
```

File: src/components/typography-control/index.js [hunk 3]
```diff
@@ -14,6 +14,9 @@ import { i18n } from 'stackable'
 import { SelectControl } from '@wordpress/components'
 
 const TypographyControl = props => {
+	const {
+		placeholder = '21',
+	} = props
```
Comment (bfintal) [inline src/components/typography-control/index.js:19]: Please move this in the defaultProps on the bottom of the file along with the other values.

File: src/util/icon/styles.js [hunk 4]
```diff
@@ -33,21 +33,24 @@ export const createIconStyleSet = ( attrNameTemplate = '%s', mainClassName = '',
...
 			width: appendImportant( getValue( 'Size', '%spx' ) ),
 			height: appendImportant( getValue( 'Size', '%spx' ) ),
 		},
-		tablet: {
+		tabletOnly: {
 			[ `.${ mainClassName } .ugb-icon-inner-svg, .${ mainClassName } .ugb-icon-inner-svg svg` ]: {
-				width: appendImportant( getValue( 'TabletSize', '%spx' ) ),
-				height: appendImportant( getValue( 'TabletSize', '%spx' ) ),
+				width: appendImportant( getValue( 'TabletSize', '%spx' ) || `${ clampedTabletSize }px` ),
+				height: appendImportant( getValue( 'TabletSize', '%spx' ) || `${ clampedMobileSize }px` ),
```
Comment (bfintal) [inline src/util/icon/styles.js:47]: It's possible for this to become `undefinedpx` if `clampedTabletSize` is `undefined`

File: src/util/icon/styles.js [hunk 5]
```diff
@@ -33,21 +33,24 @@ export const createIconStyleSet = ( attrNameTemplate = '%s', mainClassName = '',
...
 			},
 		},
 		mobile: {
 			[ `.${ mainClassName } .ugb-icon-inner-svg, .${ mainClassName } .ugb-icon-inner-svg svg` ]: {
-				width: appendImportant( getValue( 'MobileSize', '%spx' ) ),
-				height: appendImportant( getValue( 'MobileSize', '%spx' ) ),
+				width: appendImportant( getValue( 'MobileSize', '%spx' ) || `${ clampedTabletSize }px` ),
+				height: appendImportant( getValue( 'MobileSize', '%spx' ) || `${ clampedMobileSize }px` ),
```
Comment (bfintal) [inline src/util/icon/styles.js:53]: It's possible for this to become `undefinedpx` if `clampedTabletSize` is `undefined`

**Review by bfintal — APPROVED** [review]
