### PR TITLE
fix: fixes freezing when creating synced patterns

### LINKED ISSUE #3226: [WP 6.6] Card block - When saving Faded layout as a synced pattern, it freezes the editor
**Describe the bug**
- Issue inconsistently happens for other Card block layouts
- Usually happens for Faded layout
- Issue only happens if I save it as a **synced** pattern
- **Note:** Lagging/freezing also happens for other Stackable blocks but inconsistent. Please kindly check also if a fix for the Card block might fix the lagging also.

_**Saving a Synced Pattern**_

https://github.com/gambitph/Stackable/assets/103395655/3b2c47a1-873e-4f87-8633-3c3a49bd09ee

_**Adding a Synced Pattern**_

https://github.com/gambitph/Stackable/assets/103395655/4e3d2b0a-c53f-438b-a22b-b163f09c12f5

### LINKED ISSUE #3229: [WP 6.6] Lagging/freezing encountered when saving Stackable blocks as a Synced Pattern
## Freezing
- Here's a [sample set of blocks](https://github.com/user-attachments/files/16061736/timeline.inside.columns.-.lagging.issue.txt) that freezes when creating/adding to page as a new synced pattern
- Also related to: https://github.com/gambitph/Stackable/issues/3226

- Columns block with nested Timeline blocks

   https://github.com/gambitph/Stackable/assets/103395655/aae518ea-f26d-4a9c-bbed-643d893f49e7

---

## Lagging 
- Here are sample videos of the lagging that happens whether saving a nested or single block as a new synced pattern

**Actual/Issue (WP 6.6):**
- Nested:

   https://github.com/gambitph/Stackable/assets/103395655/5d75a7ab-fb5d-4058-a920-22e4d1ff5efe

- Single (no stylings):

   https://github.com/gambitph/Stackable/assets/103395655/d4925e74-4072-48d3-9c9c-71781d4b2dfc

**Expected (WP 6.5 and older):**
- Nested

   https://github.com/gambitph/Stackable/assets/103395655/90fee58b-d9a2-40cf-9c04-9d03ce034fcc

- Single (no stylings):

   https://github.com/gambitph/Stackable/assets/103395655/59624ec1-cbcc-477d-8821-5c86a02606e5

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3229 #3226

### CODE REVIEW

File: src/block-components/separator/style.js [hunk 1]
```diff
@@ -123,7 +124,7 @@ export const SeparatorStyles = props => {
 			/>
 		</>
 	)
-}
+} )
 
 const MarginBottomStyles = props => {
```
Comment (bfintal) [inline src/block-components/separator/style.js]: Do we need to memo this?

**Review by bfintal — CHANGES_REQUESTED** [review]
This fix is great but it looks like we need to do this across all style components across all block-components and blocks. For example, we'll need to create memos for the `Style` component in the Video Popup block

File: src/block/timeline/edit.js [hunk 2]
```diff
@@ -298,11 +299,18 @@ const Edit = props => {
...
 			setAttributes( { timelineIsLast: true } )
+			isUpdating.current = true
 		}
-		updateMaxHeight()
+		if ( isUpdating.current ) {
+			updateMaxHeight()
+			setTimeout( () => {
+			  isUpdating.current = false
+			}, 300 )
+		  }
```
Comment (bfintal) [inline src/block/timeline/edit.js]: When `nextBlock` changes quickly, the code will only run `updateMaxHeight()` for the first change. You may need to place it inside the `setTimeout` so it will be called at the very last change:
```suggestion
		if ( isUpdating.current ) {
			setTimeout( () => {
			  updateMaxHeight()
			  isUpdating.current = false
			}, 300 )
		  }
```

**Review by bfintal — CHANGES_REQUESTED** [review]

**Comment by andeng1106** [comment]
@mxkae @bfintal These items still has issue with stylings:

- [x] Image block
    - Stylings doesn't show on frontend
    - When copying from WP 6.6 to WP 6.5, it causes a block error
- [x] Separator
    - Stylings for the main separator doesn't show on frontend
