### PR TITLE
fix: display useful plugins tab only if user can install/activate plugins

### LINKED ISSUE #3661: Make sure helpful plugins tab is only visible if user has plugin install capabilities

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3661 

## Summary by CodeRabbit

* **Bug Fixes**
  * The "Useful Plugins" tab now only appears to users with permission to install or activate plugins.
  * UI visibility for plugin-related controls has been aligned with user capabilities to prevent unavailable actions from being shown.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: src/welcome/index.php [hunk 1]
```diff
@@ -206,10 +206,12 @@ public static function print_tabs() {
 					</a>
 				<?php } ?>
 
-				<a class="s-tab <?php echo $screen->base === 'stackable_page_stackable-useful-plugins' ? 's-active' : '' ?>"
-					href="<?php echo admin_url( 'admin.php?page=stackable-useful-plugins' ) ?>">
-					<span><?php _e( 'Useful Plugins', STACKABLE_I18N ) ?></span>
-				</a>
+				<?php if ( current_user_can( 'install_plugins' ) || current_user_can( 'activate_plugins' ) ) { ?>
```
Comment (bfintal) [inline src/welcome/index.php]:
```suggestion
				<?php if ( current_user_can( 'install_plugins' ) && current_user_can( 'activate_plugins' ) ) { ?>
```
