### PR TITLE
fix: carousel block RTL

### LINKED ISSUE #2910: Carousel block - RTL issues
**Describe the bug**
- Issues happen both in editor and frontend
- When setting WordPress site to RTL (right to left) script (e.g Arabic, Hebrew, Persian, [etc.](https://en.wikipedia.org/wiki/Right-to-left_script#:~:text=Arabic%2C%20Hebrew%2C%20Persian%2C%20Urdu%2C%20Kashmiri%2C%20Pashto%2C%20Uighur%2C%20Sorani%20Kurdish%2C%20Punjabi%2C%20and%20Sindhi%20are%20the%20most%20widespread%20RTL%20writing%20systems%20in%20modern%20times)), there are issues from the Carousel block such as:
   - [x] Issue 1 - when there are 3 or more slides to show, it doesn’t slide correctly when navigating to the last dots of the carousel 
   - [ ] Issue 2 - Default arrows are different compared when wordpress language setting is to English (happens both in editor and frontend)
- Please see screenshots section below to see the issues.

**To Reproduce**
1. Add a new page
2. Add a Carousel block
3. Add at least 9 slides or copy this block: 
[carousel 9 slide.txt](https://github.com/gambitph/Stackable/files/12811111/carousel.9.slide.txt)

4. Save page
5. See arrows if it's still the default arrow
6. View frontend page
7. Try clicking the last two dots and see if it works properly
8. Change language to Arabic (Settings > General > Site Language)
Screenshot 2023-10-05 at 8 29 24 AM

9. Repeat steps 5-7 (issue now happens since site is now RTL)

**Expected behavior**
- Issue 1 - Should be able to navigate smoothly when clicking or navigating through slides and dots
- Issue 2 - Default arrows in RTL should look the same when site is in English

**Screenshots**
_**Issue 1**_

https://github.com/gambitph/Stackable/assets/103395655/d1dc9977-8258-4bc6-b2da-177610d7808e

_**Issue 2**_

https://github.com/gambitph/Stackable/assets/103395655/9e9f8f41-c37a-4eef-b7a3-41d8cf51098f

### PR DESCRIPTION
**Pull request by mxkae**
fixes #2910

### CODE REVIEW

File: src/block/carousel/frontend-carousel.js [hunk 1]
```diff
@@ -3,6 +3,9 @@
  */
 import domReady from '@wordpress/dom-ready'
 
+const defaultIconPrev = `<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-left" class="svg-inline--fa fa-chevron-left" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" width="32" height="32"><path fill="currentColor" d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z"></path></svg>`
+const defaultIconNext = `<svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-right" class="svg-inline--fa fa-chevron-right" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" width="32" height="32"><path fill="currentColor" d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"></path></svg>`
```
Comment (bfintal) [inline src/block/carousel/frontend-carousel.js:7]: It feels off that we're defining some SVGs here. I think you're using it mainly to swap the icons for RTL, I would like to suggest grabbing the existing prev icon and next icon, then swapping them instead.

**Review by bfintal — CHANGES_REQUESTED** [review]

**Comment by andeng1106** [comment]
@mxkae Remaining issue: 
- When viewing the RTL site on iOS device (iPad & iPhone), the arrows are still not same with default.
  - Note: Tested with Xcode simulator so not sure yet if this also happens to actual iOS devices. Please confirm.
  - Issue is ok on desktop & android device
Screenshot 2023-10-25 at 5 29 51 PM
