### PR TITLE
fix (query-loop): prevent some blocks from encountering a block error inside a query loop

### LINKED ISSUE #2577: Query Loop issue - Some blocks with icons encounters a block error when placed inside Post Template
**Describe the bug**
Some blocks with icons encounters a block error (not usable)  when placed inside the Post Template from Query Loop.
 
Blocks with icons that are affected:
- Image Box
- Icon Label
- Icon Box
- Notification

Some blocks with icons that are NOT affected:
- Icon
- Accordion
- Icon List
- Map
- Blockquote

**To Reproduce**
1. Add a new page
2. Add a Query Loop block
3. In the Post Template block, add the ff. blocks mentioned in the description
4. Check if the icon in the block encounters a block error

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/103395655/216928700-fdcf0ec2-ae81-4cca-8894-832d1ef7a95c.mp4

### PR DESCRIPTION
**Pull request by prconcepcion**
Fixes #2577 , #2651

### CODE REVIEW

File: src/components/block-css/index.js [hunk 1]
```diff
@@ -338,11 +338,13 @@ const BlockCss = props => {
 			blockUniqueClassName = blockUniqueClassName + `-${ instanceId }`
 		}
 
+		if ( ! Array.isArray( selector ) ) {
```
Comment (bfintal) [inline src/components/block-css/index.js:341]: Since the fix seems to be about fixing the error when the `replace` function is not available, maybe the `if` statement should be only when `selector` is a `string` instead of checking if it's **not** an array.

**Review by bfintal — CHANGES_REQUESTED** [review]
Since the fix seems to be about fixing the error when the `replace` function is not available, maybe the `if` statement should be only when `selector` is a `string` instead of checking if it's **not** an array.

File: src/components/block-css/index.js [hunk 2]
```diff
@@ -338,11 +338,13 @@ const BlockCss = props => {
 			blockUniqueClassName = blockUniqueClassName + `-${ instanceId }`
 		}
 
+		if ( typeof selector === 'string' || selector instanceof String ) {
```
Comment (bfintal) [inline src/components/block-css/index.js:341]:
```suggestion
		if ( typeof selector === 'string' ) {
```
