### PR TITLE
fix (progress-bar): reverted previous implementation of rendering progress-value css

### LINKED ISSUE #2952: Dynamic Content & Progress Blocks issue - When getting dynamic content data from custom fields for widgets / content block / post template, it displays the number but the bar is 100%
**Describe the bug**
- When getting dynamic content data for Progress Blocks using "Current Post" and assigning the template / widget to another page, it shows the correct number value but the bar is at 100% by default.
- Might affect the ff.:
   - Widgets (Sidebar, Footer, etc.)
   - Blocksy's Content Block
   - Post Template (when using the template in Posts / Pages)
- Please check if fix for this might affect the items or fix all the items above
- Make sure to fetch a dynamic content **number** value

**To Reproduce**
_**For Widgets**_
1. Activate Blocksy
2. Go to Appearance > Widgets
3. In the Main Sidebar, add a progress block (Bar or Circle)
4. In Inspector, set Progress field to a dynamic content data (e.g. custom number field using ACF, JetEngine, or Meta Box)
5. Make sure Dynamic Source is "Current Post". Example would be like this:
Screenshot 2023-10-27 at 11 23 53 AM

6. Save widget
7. Go back to Dashboard and add a new page
8. In the number custom field, set value to 30
9. In Blocksy page settings, select a Post Structure with sidebar (4th & 5th one)
Screenshot 2023-10-27 at 12 02 27 PM

10. Save page
11. Go to frontend
12. See that the bar / circle is full (set to 100%) even if progress value is 30

**Expected behavior**

https://github.com/gambitph/Stackable/assets/103395655/7bdc781a-d76a-46f0-83fe-29d3cdd505e3

### PR DESCRIPTION
**Pull request by prconcepcion**
Created a new implementation of rendering the progress value css

fixes #2952

### CODE REVIEW

File: src/block/progress-bar/index.php [hunk 1]
```diff
@@ -19,3 +19,14 @@ function stackable_load_progressbar_frontend_script() {
 	}
 	add_action( 'stackable/progress-bar/enqueue_scripts', 'stackable_load_progressbar_frontend_script' );
 }
+
+// Remove commas when the progress value is text field from dynamic content
+if ( ! function_exists( 'stackable_progress_bar_value_remove_commas' ) ) {
+	function stackable_progress_bar_value_remove_commas( $block_content, $block ) {
+		return preg_replace_callback( '/--progress-value:[^%]+%/', function ( $matches ) {
```
Comment (bfintal) [inline src/block/progress-bar/index.php:26]: Please add a check prior to this whether `$block_content` is not null, and also only proceed if the `$block-content` string includes a comma `,` (do this in the other block too)

**Review by bfintal — CHANGES_REQUESTED** [review]

File: src/block/progress-circle/index.php [hunk 2]
```diff
@@ -19,3 +19,22 @@ function stackable_load_progresscircle_frontend_script() {
 	}
 	add_action( 'stackable/progress-circle/enqueue_scripts', 'stackable_load_progresscircle_frontend_script' );
 }
+
+// Remove commas when the progress value is text field from dynamic content
+if ( ! function_exists( 'stackable_progress_circle_value_remove_commas' ) ) {
+	function stackable_progress_circle_value_remove_commas( $block_content, $block ) {
+		if ( ! empty( $block_content ) ) {
```
Comment (bfintal) [inline src/block/progress-circle/index.php:26]:
```suggestion
		if ( empty( $block_content ) ) {
```
