### PR TITLE
Fixes onSplit function. Fixes v3 text block error

### LINKED ISSUE #1376: Block error in v3 text block
Typing in the Text inside a Card v3 block, then pressing Enter key shows block error.

### PR DESCRIPTION
**Pull request by blankart**
Fixes #1376

### CODE REVIEW

File: src/block/text/edit.js [hunk 1]
```diff
@@ -112,10 +112,24 @@ const Edit = props => {
 					tagName="p"
 					className={ textClassNames }
 					onReplace={ onReplace }
-					onSplit={ value => createBlock(
-						'stackable/text',
-						{ ...props.attributes, text: value }
-					) }
+					onSplit={ ( value, isOriginal ) => {
+						let newAttributes
```
Comment (bfintal) [inline src/block/text/edit.js:116]:
```suggestion
						// @from https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/paragraph/edit.js
						let newAttributes
```
