### PR TITLE
fix (global-typography) ensure that google fonts load when the iframe loads in FSE

### LINKED ISSUE #2615: [WP 6.2] FSE - Font Family for text blocks doesn't adapt Global Typography settings
**Describe the bug**
The same happens like in this issue: https://github.com/gambitph/Stackable/issues/2289

**To Reproduce**
1. In the Global UI Kit settings > Global Typography, add a custom font for any of the text style (Heading, Subtitle, or Body text)
Note: Global Typography settings > Apply Typography Styles to is set to **Stackable and native blocks only**
2. Active 2023 or 2022 theme
3. Go to Site Editor (Appearance > Editor)
4. Add any text block (Heading, Subtitle, Text) whether Stackable or Native
5. Observe that the font style doesn't change to what's set in Global Typography
6. Save page and compare to frontend (font family is set)

**Expected behavior**
Global Typography settings should also apply for site editor.

**Screenshots**

https://user-images.githubusercontent.com/103395655/224611839-4b75c599-0871-4dbb-a9e7-6bf3df42e0da.mp4

### PR DESCRIPTION
**Pull request by prconcepcion**
Fixes #2615

### CODE REVIEW

File: src/util/font.js [hunk 1]
```diff
@@ -46,24 +46,31 @@ const getDocumentHead = () => {
...
+
+	let index = 0
 
+	const interval = setInterval( () => {
+		index++
+		if ( index === 8 ) {
+			clearInterval( interval )
+		}
 		const headElement = getDocumentHead()
+
```
Comment (bfintal) [inline src/util/font.js:68]:
```suggestion
```
