### PR TITLE
Fixes #1036. Remove % unit

### LINKED ISSUE #1036: Padding top and bottom does not work
Padding Top & Padding Bottom does not work in separator block when unit is set to '%'

1. add a separator block
2. change padding top & bottom at Spacing
3. set unit to '%', change the value
4. see bug

### PR DESCRIPTION
**Pull request by blankart**
Fixes #1036

### CODE REVIEW

File: src/modules/advanced-block-spacing/index.js [hunk 1]
```diff
@@ -735,6 +735,8 @@ const advancedBlockSpacing = ( blockName, options = {} ) => {
 		enablePaddingRight: true,
 		enablePaddingBottom: true,
 		enablePaddingLeft: true,
+		overwritePaddingUnits: false,
+		overwriteMarginUnits: false,
```
Comment (bfintal) [inline src/modules/advanced-block-spacing/index.js:739]: Instead of doing a default value of false for `overwritePaddingUnits`, we can use `[ 'px', 'em', '%'  ]` as the default value for `overwritePaddingUnits` and then pass it directly to the Control

**Review by bfintal — CHANGES_REQUESTED** [review]
