### PR TITLE
Fix: sunset block defaults

### LINKED ISSUE #3500: Sunset Block Defaults
# Sunset Stackable Settings > Block Defaults

- Add a new option in Settings > Miscellaneous: 
  - Title: "Block Defaults (Deprecated)"
  - Description: Default state of blocks were previously allowed to be saved. This functionality has since been deprecated, and sunsetted in the future in replacement of the new Stackable Design System.
- This new option should be **disabled** by default
- If after upgrading, the user has some existing **block defaults** saved in the database, then this option should be enabled. Otherwise, leave it disabled.

# When disabled

- The **Block Defaults** panel will no longer be available
- The code that adds "default/saved" attributes from **Block defaults** should be no longer be applicable

# Implementation Notes

- Separate **ALL the code** that has to do with Block Default into a new folder in `src/deprecated/block-defaults` - these should only be loaded when the option is enabled (we can check against `get_option()` before doing a require once)

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3500

### CODE REVIEW

File: src/welcome/admin.js
Comment (DAnn2012) [inline src/welcome/admin.js:1]: Hello @mxkae

Could you include in this PR of yours these changes of mine to this file #3414  from over 5 months ago?

Thanks.

File: src/welcome/admin.js [hunk 1]
```diff
@@ -766,24 +767,24 @@ const EditorSettings = props => {
 								} }
 								help={ __( 'Adds a toolbar button for advanced copying and pasting block styles', i18n ) }
 							/>
-							<AdminToggleSetting
+							{ settings.stackable_enable_block_defaults && <AdminToggleSetting
```
Comment (bfintal) [inline src/welcome/admin.js]: @mxkae I believe this setting isn't for the block defaults, but instead is for our block layouts feature.

File: src/welcome/admin.js [hunk 2]
```diff
@@ -1514,6 +1515,17 @@ const AdditionalOptions = props => {
 									 } )
 								} }
 							/>
+							<CheckboxControl
+								label={ __( 'Block Defaults (Deprecated)', i18n ) }
+								className={ searchClassname( __( 'Block Defaults (Deprecated)', i18n ), miscellaneous ) }
+								help={ __( `Default state of blocks were previously allowed to be saved. This functionality has since been deprecated, and sunsetted in the future in replacement of the new Stackable Design System.`, i18n ) }
```
Comment (bfintal) [inline src/welcome/admin.js]:
```suggestion
								help={ __( `Default state of blocks were previously allowed to be saved. This functionality has since been sunsetted in lieu of the Stackable Design System. Use at your own risk as this feature is slated to be removed in a future version.`, i18n ) }
```

File: src/welcome/admin.js [hunk 3]
```diff
@@ -1514,6 +1515,17 @@ const AdditionalOptions = props => {
 									 } )
 								} }
 							/>
+							<CheckboxControl
+								label={ __( 'Block Defaults (Deprecated)', i18n ) }
+								className={ searchClassname( __( 'Block Defaults (Deprecated)', i18n ), miscellaneous ) }
```
Comment (bfintal) [inline src/welcome/admin.js]:
```suggestion
								className={ searchClassname( __( 'Block Defaults (Sunsetted)', i18n ), miscellaneous ) }
```

File: src/welcome/admin.js [hunk 4]
```diff
@@ -219,6 +219,7 @@ const SEARCH_TREE = [
 					__( 'Generate Global Colors for native blocks', i18n ),
 					__( 'Inherit Block Styles from theme.json', i18n ),
 					__( 'Use v3.16.0 Color Scheme Inheritance', i18n ),
+					__( 'Block Defaults (Deprecated)', i18n ),
```
Comment (bfintal) [inline src/welcome/admin.js]:
```suggestion
					__( 'Block Defaults (Sunsetted)', i18n ),
```

**Review by bfintal — CHANGES_REQUESTED** [review]

**Review by bfintal — CHANGES_REQUESTED** [review]
Add a note inside the Block Defaults panel: "Please use the Design System options instead of this. Block Defaults will be sunset and removed from a future version."

**Comment by DAnn2012** [comment]
Hello @bfintal 

Thank you for approving my PR.

I'd like to ask you, even if it's off-topic, to also take a look at this other PR #3366 (**Fixed WordPress minimum required version number to 6.5.5**) of mine.

Thank you.
