### PR TITLE
Fix: Global Settings not showing for non-admin users

### LINKED ISSUE #3531: Global Settings Not Displayed for Non-Admin Users
**Describe the bug**
When a user without an admin role logs into the site, the predefined global settings by the admin disappears.

**To Reproduce**
1. Add a User
2. Set the role as Editor
3. Login as user with editor role
4. Add a page
5. See error (color schemes, typography, global spacing and borders are not showing)

**Expected behavior**
Non-admin users should see the global settings defined in the Admin user.

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by kaeizen**
fixes #3531

### CODE REVIEW

File: src/plugins/global-settings/index.js [hunk 1]
```diff
@@ -40,13 +44,26 @@ addAction( 'stackable.global-settings.toggle-sidebar', 'toggle', () => {
 } )
 
 const GlobalSettings = () => {
+	const [ userCanManageOptions, setUserCanManageOptions ] = useState( false )
+	const id = useSelect( select => select( 'core' ).getCurrentUser().id )
```
Comment (bfintal) [inline src/plugins/global-settings/index.js]:
```suggestion
	const id = useSelect( select => select( 'core' ).getCurrentUser()?.id )
```

**Comment by bfintal** [comment]
@mxkae the saving global settings tests are failing.
